(function(root,factory){
'use strict';
var C=factory();if(typeof module==='object'&&module.exports){module.exports=C;return}var A=root.FNIQ;if(!A)return;
var DB='fniq_recovery_v1',JR='fniq_recovery_journal_v1',JP='fniq_recovery_journal_prev_v1',db=null,timer=null,candidate=null,lock=false;
A.durabilityState={mode:'checking',idb:false,ts:0};function $(id){return document.getElementById(id)}function count(){return A.state.plays.length}function plural(n,w){return n+' '+w+(n===1?'':'s')}function time(t){return t?new Date(t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'}):''}
function render(){var e=$('entryHealth'),b=$('backupStatus'),d=$('backupDetail'),r=$('recoverBackup'),ra=$('recoveryAlert'),rt=$('recoveryTitle'),rd=$('recoveryDetail'),tech=$('backupTechnical'),s=A.durabilityState,n=count(),txt=s.mode==='protected'?'Protected • '+plural(n,'play')+' • '+time(s.ts):s.mode==='saving'?'Saving… • '+plural(n,'play'):s.mode==='warning'?'Backup warning • '+plural(n,'play'):s.mode==='local'?'Saved locally • '+plural(n,'play'):'Checking recovery…';lock=true;if(e){e.textContent=txt;e.className='health '+(s.mode==='protected'?'ready':'partial')}if(b){b.textContent=s.mode==='warning'?'BACKUP WARNING':s.idb?'AUTO-SAVE ON':'BROWSER SAVE ON';b.className='tinybadge '+(s.mode==='warning'?'safetyWarnBadge':'safetyOkBadge')}if(d){if(s.mode==='protected')d.innerHTML='<strong>✓ Your game is safe.</strong><span>'+plural(n,'play')+' saved automatically'+(s.ts?' • Last saved '+time(s.ts):'')+'.</span>';else if(s.mode==='saving')d.innerHTML='<strong>Saving now…</strong><span>'+plural(n,'play')+' in the current game.</span>';else if(s.mode==='warning')d.innerHTML='<strong>⚠ Backup warning.</strong><span>Your recovery copy is available, but the main browser save reported a problem. Download a backup file now.</span>';else if(s.mode==='local')d.innerHTML='<strong>Your game is saved in this browser.</strong><span>Automatic recovery storage is unavailable. Download a backup file before kickoff and at quarter breaks.</span>';else d.innerHTML='<strong>Checking your saved game…</strong><span>This should only take a moment.</span>'}if(tech)tech.textContent=s.idb?'Friday Night IQ keeps the normal browser save, a separate recovery database, and rolling play snapshots.':'Friday Night IQ is using the normal browser save. The separate recovery database is unavailable on this browser.';if(candidate){var cn=candidate.playCount||0,ct=time(candidate.ts),more=cn>n;if(rt)rt.textContent=more?'Newer auto-save found':'Auto-save available';if(rd)rd.textContent='Current screen: '+plural(n,'play')+'. Auto-save: '+plural(cn,'play')+(ct?' from '+ct:'')+'. '+(more?'If plays disappeared, recover this copy.':'Use this only if you need to return to that saved copy.');if(r){r.textContent='Recover '+plural(cn,'play');r.classList.remove('hidden')}if(ra)ra.classList.remove('hidden')}else{if(r)r.classList.add('hidden');if(ra)ra.classList.add('hidden')}setTimeout(function(){lock=false},0)}A.renderDurabilityStatus=render;
function mode(m,ts){A.durabilityState.mode=m;A.durabilityState.ts=ts||A.durabilityState.ts;render()}
function inject(){if($('gameSafety'))return;var h=document.querySelector('#setup .grid2 > div');if(!h)return;var c=document.createElement('div');c.id='gameSafety';c.className='card safetyCard';c.innerHTML='<div class="cardhead"><div><h2 class="section">Backups & Recovery</h2><p class="muted">Friday Night IQ saves automatically while you chart.</p></div><span id="backupStatus" class="tinybadge">Checking…</span></div><div id="backupDetail" class="safetySummary"><strong>Checking your saved game…</strong><span>This should only take a moment.</span></div><div id="recoveryAlert" class="recoveryAlert hidden"><div><strong id="recoveryTitle">Auto-save found</strong><div id="recoveryDetail" class="muted"></div></div><button id="recoverBackup" class="btn recoveryBtn hidden" type="button">Recover Auto-Save</button></div><div class="safetyActions"><div class="safetyAction"><button id="downloadBackup" class="btn primary full" type="button">Download Backup File</button><span>Keep a copy outside the browser.</span></div><div class="safetyAction"><label for="restoreBackup" class="btn full">Restore From Backup File</label><span>Use a .fniq.json file you downloaded earlier.</span></div><input id="restoreBackup" type="file" accept=".json,.fniq.json,application/json" style="display:none"></div><details class="backupHow"><summary>How automatic backup works</summary><p id="backupTechnical" class="muted">Checking recovery storage…</p></details>';h.appendChild(c);$('downloadBackup').onclick=download;$('restoreBackup').onchange=restoreFile;$('recoverBackup').onclick=recover;render()}
function guard(){var e=$('entryHealth');if(!e||e.dataset.guard)return;e.dataset.guard='1';new MutationObserver(function(){if(!lock)render()}).observe(e,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}
function quietQB(){var b=$('qbButton');if(!b||b.dataset.quiet)return;b.dataset.quiet='1';b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var q=(A.state.roster||[]).filter(function(p){return String(p.position||'').toUpperCase()==='QB'}).map(function(p){return'#'+p.number+' '+p.name});if(!q.length){A.msg&&A.msg('Add a QB to roster');return}var i=q.indexOf(A.state.activeQB);A.state.activeQB=q[(i+1+q.length)%q.length];A.save('qb');b.textContent='QB: '+A.state.activeQB.split(' ')[0]},true)}
function open(){return new Promise(function(ok,no){if(!root.indexedDB)return no(new Error('IndexedDB unavailable'));var r=indexedDB.open(DB,1);r.onupgradeneeded=function(){var x=r.result;if(!x.objectStoreNames.contains('latest'))x.createObjectStore('latest',{keyPath:'key'});if(!x.objectStoreNames.contains('snapshots'))x.createObjectStore('snapshots',{keyPath:'id',autoIncrement:true})};r.onsuccess=function(){db=r.result;ok()};r.onerror=function(){no(r.error)}})}
function rec(state,why){var s=C.clone(state);return{ts:Date.now(),reason:why||'state',playCount:s.plays.length,gameId:s.meta&&s.meta.gameId||'',state:s}}
function putLatest(x){return new Promise(function(ok,no){var t=db.transaction('latest','readwrite');t.objectStore('latest').put(Object.assign({key:'current'},x));t.oncomplete=function(){ok(x)};t.onerror=function(){no(t.error)}})}
function addSnap(x){return new Promise(function(ok,no){var t=db.transaction('snapshots','readwrite');t.objectStore('snapshots').add(x);t.oncomplete=function(){ok(x)};t.onerror=function(){no(t.error)}})}
function getLatest(){return new Promise(function(ok){if(!db)return ok(null);var r=db.transaction('latest').objectStore('latest').get('current');r.onsuccess=function(){ok(r.result||null)};r.onerror=function(){ok(null)}})}
function getSnap(){return new Promise(function(ok){if(!db)return ok(null);var r=db.transaction('snapshots').objectStore('snapshots').openCursor(null,'prev');r.onsuccess=function(){ok(r.result?r.result.value:null)};r.onerror=function(){ok(null)}})}
function journal(x){try{var old=localStorage.getItem(JR),s=C.clone(x);if(s.state.branding)s.state.branding.logo='';if(old)localStorage.setItem(JP,old);localStorage.setItem(JR,JSON.stringify(s))}catch(e){}}
function journals(){var a=[];[JR,JP].forEach(function(k){try{var x=JSON.parse(localStorage.getItem(k)||'null');if(x&&C.validState(x.state))a.push(x)}catch(e){}});return a}
function eligible(x){if(!x||!x.playCount||!C.validState(x.state))return false;var n=count(),id=A.state.meta&&A.state.meta.gameId||'',ts=A.state.meta&&A.state.meta.updatedAt||0;if(A.loadStatus&&A.loadStatus.parseError)return true;if(A.loadStatus&&!A.loadStatus.hadPrimary)return true;if(x.gameId===id&&(x.playCount>n||(x.ts>ts+1500&&x.playCount>=n)))return true;return n===0&&x.playCount>0&&Date.now()-x.ts<21600000}
function choose(a){return a.filter(eligible).sort(function(x,y){return y.ts-x.ts})[0]||null}
function apply(s,msg){A.replaceState(s,'recovery');A.durabilitySnapshot('recovery');A.renderSetup&&A.renderSetup();A.hydrateSituation&&A.hydrateSituation();A.resetEntry&&A.resetEntry();A.renderAll&&A.renderAll();A.screen&&A.screen('live');candidate=null;render();A.msg&&A.msg(msg||('Recovered '+plural(count(),'play')))}
function recover(){if(!candidate)return;var cn=candidate.playCount||0,cur=count(),ct=time(candidate.ts),q='Recover '+plural(cn,'play')+(ct?' from '+ct:'')+'? This will replace the '+plural(cur,'play')+' currently on screen.';if(root.confirm(q))apply(candidate.state,'Recovered '+plural(cn,'play')+' from auto-save')}
function name(){return C.backupName(A.state.setup||{})}
function download(){var p=C.makePayload(A.state,'safety16'),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name();document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u)},1000);A.msg&&A.msg('Backup file downloaded • '+plural(count(),'play'))}
function restoreFile(e){var f=e.target.files&&e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var p=C.parsePayload(String(r.result||'')),n=p.state.plays.length;if(root.confirm('Restore this backup with '+plural(n,'play')+'? This replaces the current game on this browser.'))apply(p.state,'Backup file restored • '+plural(n,'play'))}catch(err){A.msg&&A.msg('Backup could not be restored: '+err.message)}e.target.value=''};r.onerror=function(){A.msg&&A.msg('Backup file could not be read');e.target.value=''};r.readAsText(f)}
A.durabilityMirror=function(why){mode('saving');var x=rec(A.state,why);clearTimeout(timer);timer=setTimeout(function(){if(!db){mode(A.primarySaveError?'warning':'local',Date.now());return}putLatest(x).then(function(){mode(A.primarySaveError?'warning':'protected',x.ts)}).catch(function(){mode('local',Date.now())})},80)};
A.durabilitySnapshot=function(why,state){var x=rec(state||A.state,why);journal(x);if(!db){mode(A.primarySaveError?'warning':'local',Date.now());return Promise.resolve(x)}return addSnap(x).then(function(){return why==='pre-reset'?x:putLatest(x)}).then(function(){mode(A.primarySaveError?'warning':'protected',x.ts);return x}).catch(function(){mode('local',Date.now());return x})};
A.initDurability=function(){inject();guard();quietQB();return open().then(function(){A.durabilityState.idb=true;return Promise.all([getLatest(),getSnap()])}).then(function(a){candidate=choose(a.concat(journals()));if(A.loadStatus&&A.loadStatus.parseError&&candidate){apply(candidate.state,'Primary save repaired from auto-save');return}render();A.durabilityMirror('startup')}).catch(function(){A.durabilityState.idb=false;candidate=choose(journals());if(A.loadStatus&&A.loadStatus.parseError&&candidate)apply(candidate.state,'Primary save repaired from recovery journal');else mode(A.primarySaveError?'warning':'local',Date.now())})};
})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';function clone(x){return JSON.parse(JSON.stringify(x))}function validState(s){return!!(s&&typeof s==='object'&&s.setup&&Array.isArray(s.plays)&&s.current&&typeof s.current==='object')}function makePayload(s,v){if(!validState(s))throw new Error('Current game state is invalid');var c=clone(s);return{format:'FNIQ_GAME_BACKUP',version:1,appVersion:v||'',exportedAt:new Date().toISOString(),gameId:c.meta&&c.meta.gameId||'',playCount:c.plays.length,state:c}}function parsePayload(t){var p;try{p=JSON.parse(t)}catch(e){throw new Error('Not valid JSON')}if(validState(p))p={format:'FNIQ_GAME_BACKUP',version:1,playCount:p.plays.length,state:p};if(!p||p.format!=='FNIQ_GAME_BACKUP'||!validState(p.state))throw new Error('Not a Friday Night IQ game backup');if(p.playCount!=null&&Number(p.playCount)!==p.state.plays.length)throw new Error('Backup play count does not match');return p}function backupName(setup){setup=setup||{};var team=String(setup.team||'team').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'team',raw=String(setup.date||''),m,d;if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){var a=raw.split('-');m=Number(a[1]);d=Number(a[2])}else{var now=new Date();m=now.getMonth()+1;d=now.getDate()}return team+'.'+m+'.'+d+'.fniq.json'}return{clone:clone,validState:validState,makePayload:makePayload,parsePayload:parsePayload,backupName:backupName}});
