(function(root,factory){
'use strict';
var C=factory();if(typeof module==='object'&&module.exports){module.exports=C;return}var A=root.FNIQ;if(!A)return;
var DB='fniq_recovery_v1',JR='fniq_recovery_journal_v1',JP='fniq_recovery_journal_prev_v1',db=null,timer=null,candidate=null,lock=false;
A.durabilityState={mode:'checking',idb:false,ts:0};function $(id){return document.getElementById(id)}function count(){return A.state.plays.length}function time(t){return t?new Date(t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'}):''}
function render(){var e=$('entryHealth'),b=$('backupStatus'),d=$('backupDetail'),r=$('recoverBackup'),s=A.durabilityState,txt=s.mode==='protected'?'Protected • '+count()+' plays • '+time(s.ts):s.mode==='saving'?'Saving… • '+count()+' plays':s.mode==='warning'?'Protected backup • primary warning':s.mode==='local'?'Saved locally • '+count()+' plays':'Checking recovery…';lock=true;if(e){e.textContent=txt;e.className='health '+(s.mode==='protected'?'ready':'partial')}if(b)b.textContent=s.idb?'Auto backup ON':'Local save';if(d)d.textContent=(s.idb?'Primary browser save + IndexedDB mirror + rolling play snapshots.':'Primary browser save active; IndexedDB recovery unavailable.')+' Download a Game Backup at quarter breaks.'+(candidate?' Recovery available: '+candidate.playCount+' plays from '+time(candidate.ts)+'.':'');if(r)r.classList.toggle('hidden',!candidate);setTimeout(function(){lock=false},0)}A.renderDurabilityStatus=render;
function mode(m,ts){A.durabilityState.mode=m;A.durabilityState.ts=ts||A.durabilityState.ts;render()}
function inject(){if($('gameSafety'))return;var h=document.querySelector('#setup .grid2 > div');if(!h)return;var c=document.createElement('div');c.id='gameSafety';c.className='card';c.innerHTML='<div class="cardhead"><div><h2 class="section">Game safety</h2><p class="muted">Automatic recovery plus a manual file backup.</p></div><span id="backupStatus" class="tinybadge">Checking…</span></div><div id="backupDetail" class="notice">Checking recovery storage…</div><div class="buttonrow"><button id="downloadBackup" class="btn primary" type="button">Download Game Backup</button><label for="restoreBackup" class="btn">Restore Backup</label><input id="restoreBackup" type="file" accept=".json,.fniq.json,application/json" style="display:none"><button id="recoverBackup" class="btn hidden" type="button">Recover Protected Copy</button></div>';h.appendChild(c);$('downloadBackup').onclick=download;$('restoreBackup').onchange=restoreFile;$('recoverBackup').onclick=recover;render()}
function guard(){var e=$('entryHealth');if(!e||e.dataset.guard)return;e.dataset.guard='1';new MutationObserver(function(){if(!lock)render()}).observe(e,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}
function quietQB(){var b=$('qbButton');if(!b||b.dataset.quiet)return;b.dataset.quiet='1';b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var q=(A.state.roster||[]).filter(function(p){return String(p.position||'').toUpperCase()==='QB'}).map(function(p){return'#'+p.number+' '+p.name});if(!q.length){A.msg&&A.msg('Add a QB to roster');return}var i=q.indexOf(A.state.activeQB);A.state.activeQB=q[(i+1+q.length)%q.length];A.save('qb');b.textContent='QB: '+A.state.activeQB.split(' ')[0]},true)}
function open(){return new Promise(function(ok,no){if(!root.indexedDB)return no(new Error('IndexedDB unavailable'));var r=indexedDB.open(DB,1);r.onupgradeneeded=function(){var x=r.result;if(!x.objectStoreNames.contains('latest'))x.createObjectStore('latest',{keyPath:'key'});if(!x.objectStoreNames.contains('snapshots'))x.createObjectStore('snapshots',{keyPath:'id',autoIncrement:true})};r.onsuccess=function(){db=r.result;ok()};r.onerror=function(){no(r.error)}})}
function rec(state,why){var s=C.clone(state);return{ts:Date.now(),reason:why||'state',playCount:s.plays.length,gameId:s.meta&&s.meta.gameId||'',state:s}}
function putLatest(x){return new Promise(function(ok,no){var t=db.transaction('latest','readwrite');t.objectStore('latest').put(Object.assign({key:'current'},x));t.oncomplete=function(){ok(x)};t.onerror=function(){no(t.error)}})}
function addSnap(x){return new Promise(function(ok,no){var t=db.transaction('snapshots','readwrite');t.objectStore('snapshots').add(x);t.oncomplete=function(){ok(x)};t.onerror=function(){no(t.error)}})}
function getLatest(){return new Promise(function(ok){if(!db)return ok(null);var r=db.transaction('latest').objectStore('latest').get('current');r.onsuccess=function(){ok(r.result||null)};r.onerror=function(){ok(null)}})}
function getSnap(){return new Promise(function(ok){if(!db)return ok(null);var r=db.transaction('snapshots').objectStore('snapshots').openCursor(null,'prev');r.onsuccess=function(){ok(r.result?r.result.value:null)};r.onerror=function(){ok(null)}})}
function journal(x){try{var old=localStorage.getItem(JR),s=C.clone(x);if(s.state.branding)s.state.branding.logo='';if(old)localStorage.setItem(JP,old);localStorage.setItem(JR,JSON.stringify(s))}catch(e){}}
function journals(){var a=[];[JR,JP].forEach(function(k){try{var x=JSON.parse(localStorage.getItem(k)||'null');if(x&&C.validState(x.state))a.push(x)}catch(e){}});return a}
function eligible(x){if(!x||!x.playCount||!C.validState(x.state))return false;var n=count(),id=A.state.meta&&A.state.meta.gameId||'',ts=A.state.meta&&A.state.meta.updatedAt||0;if(A.loadStatus&&A.loadStatus.parseError)return true;if(A.loadStatus&&!A.loadStatus.hadPrimary)return true;if(x.gameId===id&&(x.playCount>n||(x.ts>ts+1500&&x.playCount>=n)))return true;return n===0&&x.playCount>0&&Date.now()-x.ts<21600000}
function choose(a){return a.filter(eligible).sort(function(x,y){return y.ts-x.ts})[0]||null}
function apply(s,msg){A.replaceState(s,'recovery');A.durabilitySnapshot('recovery');A.renderSetup&&A.renderSetup();A.hydrateSituation&&A.hydrateSituation();A.resetEntry&&A.resetEntry();A.renderAll&&A.renderAll();A.screen&&A.screen('live');candidate=null;render();A.msg&&A.msg(msg||('Recovered '+count()+' plays'))}
function recover(){if(candidate&&root.confirm('Recover the protected '+candidate.playCount+'-play copy? This replaces the current in-browser game.'))apply(candidate.state,'Protected game copy recovered')}
function name(){var s=A.state.setup||{};return((s.team||'team')+'-vs-'+(s.opp||'opponent')+'-'+(s.date||'game')).replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'.fniq.json'}
function download(){var p=C.makePayload(A.state,'safety1'),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name();document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u)},1000);A.msg&&A.msg('Game backup downloaded • '+count()+' plays')}
function restoreFile(e){var f=e.target.files&&e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var p=C.parsePayload(String(r.result||'')),n=p.state.plays.length;if(root.confirm('Restore this backup with '+n+' plays? This replaces the current in-browser game.'))apply(p.state,'Backup restored • '+n+' plays')}catch(err){A.msg&&A.msg('Backup could not be restored: '+err.message)}e.target.value=''};r.onerror=function(){A.msg&&A.msg('Backup file could not be read');e.target.value=''};r.readAsText(f)}
A.durabilityMirror=function(why){mode('saving');var x=rec(A.state,why);clearTimeout(timer);timer=setTimeout(function(){if(!db){mode(A.primarySaveError?'warning':'local',Date.now());return}putLatest(x).then(function(){mode(A.primarySaveError?'warning':'protected',x.ts)}).catch(function(){mode('local',Date.now())})},80)};
A.durabilitySnapshot=function(why,state){var x=rec(state||A.state,why);journal(x);if(!db){mode(A.primarySaveError?'warning':'local',Date.now());return Promise.resolve(x)}return addSnap(x).then(function(){return why==='pre-reset'?x:putLatest(x)}).then(function(){mode(A.primarySaveError?'warning':'protected',x.ts);return x}).catch(function(){mode('local',Date.now());return x})};
A.initDurability=function(){inject();guard();quietQB();return open().then(function(){A.durabilityState.idb=true;return Promise.all([getLatest(),getSnap()])}).then(function(a){candidate=choose(a.concat(journals()));if(A.loadStatus&&A.loadStatus.parseError&&candidate){apply(candidate.state,'Primary save repaired from protected copy');return}render();A.durabilityMirror('startup')}).catch(function(){A.durabilityState.idb=false;candidate=choose(journals());if(A.loadStatus&&A.loadStatus.parseError&&candidate)apply(candidate.state,'Primary save repaired from recovery journal');else mode(A.primarySaveError?'warning':'local',Date.now())})};
})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';function clone(x){return JSON.parse(JSON.stringify(x))}function validState(s){return!!(s&&typeof s==='object'&&s.setup&&Array.isArray(s.plays)&&s.current&&typeof s.current==='object')}function makePayload(s,v){if(!validState(s))throw new Error('Current game state is invalid');var c=clone(s);return{format:'FNIQ_GAME_BACKUP',version:1,appVersion:v||'',exportedAt:new Date().toISOString(),gameId:c.meta&&c.meta.gameId||'',playCount:c.plays.length,state:c}}function parsePayload(t){var p;try{p=JSON.parse(t)}catch(e){throw new Error('Not valid JSON')}if(validState(p))p={format:'FNIQ_GAME_BACKUP',version:1,playCount:p.plays.length,state:p};if(!p||p.format!=='FNIQ_GAME_BACKUP'||!validState(p.state))throw new Error('Not a Friday Night IQ game backup');if(p.playCount!=null&&Number(p.playCount)!==p.state.plays.length)throw new Error('Backup play count does not match');return p}return{clone:clone,validState:validState,makePayload:makePayload,parsePayload:parsePayload}});
