(function(root,factory){
'use strict';
var C=factory();
if(typeof module==='object'&&module.exports){module.exports=C;return;}
if(root.FNIQ)C.install(root.FNIQ,root);
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

var DEFS=[
 {key:'down',category:'Down',fixed:['1','2','3','4']},
 {key:'firstDownSituation',category:'First down situation',fixed:['Ten','Long','Medium','Short']},
 {key:'distanceBucket',category:'Distance',fixed:['Short','Medium','Long']},
 {key:'formation',category:'Formation'},
 {key:'front',category:'Front'},
 {key:'coverage',category:'Post-snap coverage'},
 {key:'blitz',category:'Blitz',fixed:['Yes','No']},
 {key:'hash',category:'Hash',fixed:['Left','Middle','Right']},
 {key:'pressure',category:'Blitz type'},
 {key:'preCoverage',category:'Pre-snap coverage'},
 {key:'safeties',category:'High safeties'},
 {key:'box',category:'Box'},
 {key:'personnel',category:'Personnel'},
 {key:'motion',category:'Motion'},
 {key:'playType',category:'Play type',fixed:['Run','Pass']},
 {key:'runType',category:'Run Type'},
 {key:'passDepth',category:'Pass depth'},
 {key:'conceptFamily',category:'Concept family'},
 {key:'concept',category:'Specific concept'},
 {key:'direction',category:'Direction',fixed:['Left','Middle','Right']},
 {key:'fieldZone',category:'Field zone',fixed:['Own Territory','Midfield','Plus Territory','Red Zone','Goal To Go']},
 {key:'quarter',category:'Quarter',fixed:['Q1','Q2','Q3','Q4','OT']},
 {key:'exactDistance',category:'Exact distance'},
 {key:'drive',category:'Drive'},
 {key:'scoreState',category:'Score state',fixed:['Leading','Tied','Trailing']},
 {key:'result',category:'Result',fixed:['Success','First Down','Explosive','Touchdown','Turnover','Interception','Fumble','Fumble Lost','Penalty']}
];
var SPLIT_PRIORITY=['formation','hash','blitz','pressure','coverage','front','playType','runType','conceptFamily','motion','personnel','safeties','box','direction','fieldZone','preCoverage','passDepth'];

function known(v){return v!=null&&v!==''&&v!=='NA'&&v!=='Unknown'&&v!=='Unknown / N/A';}
function pct(a,b){return b?Math.round(a/b*100):0;}
function avg(a){return a.length?a.reduce(function(s,x){return s+x;},0)/a.length:0;}
function distanceBucket(d){d=Number(d)||10;return d<=3?'Short':d<=7?'Medium':'Long';}
function firstDownSituation(down,distance){down=Number(down);distance=Number(distance);if(down!==1)return null;if(distance===10)return'Ten';if(distance>10)return'Long';if(distance<=3)return'Short';return'Medium';}
function resolvedCoverage(p){var x=p&&p.postCoverage;if(known(x))return x==='Same as pre-snap'?(p.coverage||'NA'):x;return p&&p.coverage||'NA';}
function isBlitz(p){return known(p&&p.pressure)&&p.pressure!=='None';}
function fieldZone(E,p){var a=E.fieldAbs(p.fieldSide,p.yardLine);return a>=90?'Goal To Go':a>=80?'Red Zone':a>=60?'Plus Territory':a>=40?'Midfield':'Own Territory';}
function scoreState(p){var s=p&&p.scoreBefore;if(!s)return'Unknown';var d=(Number(s.us)||0)-(Number(s.them)||0);return d>0?'Leading':d<0?'Trailing':'Tied';}
function hasTag(p,t){return Array.isArray(p&&p.tags)&&p.tags.indexOf(t)>=0;}
function resultFlags(E,p,isExplosive){var a=[];if(E.success(p))a.push('Success');if(E.isFirstDownResult(p))a.push('First Down');if((isExplosive&&isExplosive(p))||hasTag(p,'Explosive'))a.push('Explosive');if(hasTag(p,'Touchdown'))a.push('Touchdown');if(hasTag(p,'Turnover')||p.passResult==='Interception'||hasTag(p,'Fumble Lost'))a.push('Turnover');if(p.passResult==='Interception'||hasTag(p,'Interception'))a.push('Interception');if(hasTag(p,'Fumble'))a.push('Fumble');if(hasTag(p,'Fumble Lost'))a.push('Fumble Lost');if(p.penalty)a.push('Penalty');return a;}
function statPlays(E,plays){return(plays||[]).filter(function(p){if(p.playType!=='Run'&&p.playType!=='Pass')return false;if(p.penalty&&p.penalty.status==='Accepted'&&p.penalty.timing==='DEAD')return false;return true;});}
function schemePlays(E,plays){return statPlays(E,plays).filter(function(p){return!(p.penalty&&p.penalty.status==='Accepted');});}
function valueFor(E,p,key){
 if(key==='down')return String(p.down);if(key==='firstDownSituation')return firstDownSituation(p.down,p.distance);if(key==='distanceBucket')return distanceBucket(p.distance);if(key==='formation')return p.formation;if(key==='front')return p.front;if(key==='coverage')return resolvedCoverage(p);if(key==='blitz')return isBlitz(p)?'Yes':known(p.pressure)?'No':'Unknown';if(key==='hash')return p.hash;if(key==='pressure')return p.pressure;if(key==='preCoverage')return p.coverage;if(key==='safeties')return String(p.safeties);if(key==='box')return String(p.box);if(key==='personnel')return p.personnel;if(key==='motion')return p.motion;if(key==='playType')return p.playType;if(key==='runType')return p.playType==='Run'?p.attackDetail:'NA';if(key==='passDepth')return p.playType==='Pass'?p.attackDetail:'NA';if(key==='conceptFamily')return p.conceptFamily;if(key==='concept')return p.concept;if(key==='direction')return p.direction;if(key==='fieldZone')return fieldZone(E,p);if(key==='quarter')return p.quarter;if(key==='exactDistance')return String(p.distance);if(key==='drive')return String(p.drive);if(key==='scoreState')return scoreState(p);return null;
}
function display(key,v){if(key==='down')return v==='1'?'1st Down':v==='2'?'2nd Down':v==='3'?'3rd Down':'4th Down';if(key==='firstDownSituation')return v==='Ten'?'1st & 10':v==='Long'?'1st & Long':v==='Short'?'1st & Short':'1st & Medium';if(key==='front')return v+' Down';if(key==='blitz')return v==='Yes'?'Blitz':'No Blitz';if(key==='safeties')return v+' High';if(key==='box')return v+' Box';if(key==='exactDistance')return v+' yards to go';if(key==='drive')return'Drive '+v;return v;}
function defFor(key){return DEFS.find(function(d){return d.key===key;});}
function distinct(plays,fn){var seen={},out=[];(plays||[]).forEach(function(p){var v=fn(p);if(!known(v)||seen[String(v)])return;seen[String(v)]=1;out.push(String(v));});return out;}
function valuesFor(E,plays,def){if(def.fixed)return def.fixed.slice();var out=distinct(plays,function(p){return valueFor(E,p,def.key);});if(['exactDistance','drive','safeties','box','front'].indexOf(def.key)>=0)out.sort(function(a,b){return Number(a)-Number(b);});else out.sort();return out;}
function matches(E,p,f,isExplosive){if(f.key==='result')return resultFlags(E,p,isExplosive).indexOf(f.value)>=0;return String(valueFor(E,p,f.key))===String(f.value);}
function filterPlays(E,plays,filters,isExplosive){return(plays||[]).filter(function(p){return(filters||[]).every(function(f){return matches(E,p,f,isExplosive);});});}
function groupBy(E,plays,key,isExplosive){var g={};(plays||[]).forEach(function(p){var vals=key==='result'?resultFlags(E,p,isExplosive):[valueFor(E,p,key)];vals.forEach(function(v){if(!known(v)||v==='Unknown')return;(g[String(v)]||(g[String(v)]=[])).push(p);});});return g;}
function distribution(E,plays,key,isExplosive){var g=groupBy(E,plays,key,isExplosive),den=key==='result'?(plays||[]).length:Object.keys(g).reduce(function(s,k){return s+g[k].length;},0);return Object.keys(g).map(function(v){var a=g[v],sp=statPlays(E,a);return{key:key,value:v,label:display(key,v),n:a.length,share:pct(a.length,den),ypp:avg(sp.map(E.officialNetYards)),success:pct(sp.filter(E.success).length,sp.length)};}).sort(function(a,b){return b.n-a.n||a.label.localeCompare(b.label);});}
function compareDistribution(E,subset,all,key,isExplosive){var base=distribution(E,all,key,isExplosive),map={};base.forEach(function(r){map[r.value]=r.share;});return distribution(E,subset,key,isExplosive).map(function(r){r.baseline=map[r.value]||0;r.delta=r.share-r.baseline;return r;});}
function confidence(n){return n>=8?'Higher':n>=4?'Medium':'Low';}
function summary(E,plays,isExplosive){var sp=statPlays(E,plays),runs=sp.filter(function(p){return p.playType==='Run';}),passes=sp.filter(function(p){return p.playType==='Pass';});return{plays:sp.length,ypp:avg(sp.map(E.officialNetYards)),success:pct(sp.filter(E.success).length,sp.length),runs:runs.length,passes:passes.length,runYpp:avg(runs.map(E.officialNetYards)),passYpp:avg(passes.map(E.officialNetYards)),runSuccess:pct(runs.filter(E.success).length,runs.length),passSuccess:pct(passes.filter(E.success).length,passes.length),explosives:sp.filter(function(p){return(isExplosive&&isExplosive(p))||hasTag(p,'Explosive');}).length,turnovers:sp.filter(function(p){return hasTag(p,'Turnover')||hasTag(p,'Fumble Lost')||p.passResult==='Interception';}).length};}
function answerCandidates(E,plays){var sp=schemePlays(E,plays),defs=[{key:'playType',label:'Play type'},{key:'runType',label:'Run Type'},{key:'conceptFamily',label:'Concept'},{key:'concept',label:'Call'}],out=[];defs.forEach(function(def){var g=groupBy(E,sp,def.key);Object.keys(g).forEach(function(v){var a=g[v];if(a.length<2)return;var y=avg(a.map(E.officialNetYards)),s=pct(a.filter(E.success).length,a.length);out.push({key:def.key,value:v,label:display(def.key,v),kind:def.label,n:a.length,ypp:y,success:s,confidence:confidence(a.length),score:y*0.65+s*0.035});});});return out;}
function bestAnswers(E,plays){var a=answerCandidates(E,plays);return{best:a.slice().sort(function(x,y){return y.score-x.score||y.n-x.n;}).slice(0,3),worst:a.slice().sort(function(x,y){return x.score-y.score||y.n-x.n;}).slice(0,2)};}
function filterEq(a,b){return a.key===b.key&&String(a.value)===String(b.value);}
function mergeFilters(a,b){var out=(a||[]).map(function(x){return Object.assign({},x);});(b||[]).forEach(function(f){var i=out.findIndex(function(x){return x.key===f.key;});if(i>=0)out[i]=Object.assign({},f);else out.push(Object.assign({},f));});return out;}
function adaptiveContext(E,plays,desired,isExplosive){var mandatory=(desired||[]).filter(function(f){return f.key==='down'||f.key==='distanceBucket'||f.key==='firstDownSituation';}),optional=(desired||[]).filter(function(f){return f.key!=='down'&&f.key!=='distanceBucket'&&f.key!=='firstDownSituation';}),filters=mandatory.concat(optional),rows=filterPlays(E,plays,filters,isExplosive),broadened=false;while(!rows.length&&optional.length){optional.pop();filters=mandatory.concat(optional);rows=filterPlays(E,plays,filters,isExplosive);broadened=true;}if(!rows.length&&mandatory.some(function(f){return f.key==='firstDownSituation';}))return{filters:mandatory,plays:[],broadened:broadened};if(!rows.length&&mandatory.length>1){filters=mandatory.filter(function(f){return f.key==='down';});rows=filterPlays(E,plays,filters,isExplosive);broadened=true;}if(!rows.length){filters=[];rows=(plays||[]).slice();broadened=true;}return{filters:filters,plays:rows,broadened:broadened};}
function rate(E,plays,key,value,isExplosive){var d=distribution(E,plays,key,isExplosive),r=d.find(function(x){return String(x.value)===String(value);});return r?r.share:0;}
function trendSignals(E,plays,isExplosive){var rows=(plays||[]).slice(),drives=Array.from(new Set(rows.map(function(p){return Number(p.drive)||0;}).filter(Boolean))).sort(function(a,b){return a-b;}),prior=[],recent=[],windowLabel='recent snaps';if(drives.length>=4){var pds=drives.slice(-4,-2),rds=drives.slice(-2);prior=rows.filter(function(p){return pds.indexOf(Number(p.drive))>=0;});recent=rows.filter(function(p){return rds.indexOf(Number(p.drive))>=0;});windowLabel='last 2 drives';}else if(rows.length>=8){var cut=Math.floor(rows.length/2);prior=rows.slice(0,cut);recent=rows.slice(cut);}else return[];var signals=[];var bp=distribution(E,prior,'blitz',isExplosive),br=distribution(E,recent,'blitz',isExplosive),pn=bp.reduce(function(s,x){return s+x.n;},0),rn=br.reduce(function(s,x){return s+x.n;},0);if(pn>=2&&rn>=2){var oldB=rate(E,prior,'blitz','Yes',isExplosive),newB=rate(E,recent,'blitz','Yes',isExplosive),bd=newB-oldB;if(Math.abs(bd)>=20)signals.push({kind:'Blitz',label:'Blitz',previous:oldB,current:newB,delta:bd,window:windowLabel,confidence:confidence(Math.min(pn,rn))});}['front','coverage'].forEach(function(key){var pd=distribution(E,prior,key,isExplosive),rd=distribution(E,recent,key,isExplosive),pden=pd.reduce(function(s,x){return s+x.n;},0),rden=rd.reduce(function(s,x){return s+x.n;},0);if(pden<2||rden<2)return;var vals={};pd.concat(rd).forEach(function(x){vals[x.value]=1;});Object.keys(vals).forEach(function(v){var old=rate(E,prior,key,v,isExplosive),now=rate(E,recent,key,v,isExplosive),delta=now-old;if(Math.abs(delta)>=25)signals.push({kind:key,label:display(key,v),previous:old,current:now,delta:delta,window:windowLabel,confidence:confidence(Math.min(pden,rden))});});});return signals.sort(function(a,b){return Math.abs(b.delta)-Math.abs(a.delta);}).slice(0,4);}
function suggestDimensions(E,plays,filters,isExplosive){var used={};(filters||[]).forEach(function(f){used[f.key]=1;});return SPLIT_PRIORITY.map(function(key,i){var rows=distribution(E,plays,key,isExplosive);return{key:key,rows:rows,score:100-i};}).filter(function(x){return!used[x.key]&&x.rows.length>=2;}).sort(function(a,b){return b.score-a.score;}).slice(0,7);}
function pinKey(filters){return(filters||[]).map(function(f){return f.key+'='+f.value;}).sort().join('|');}
function deltaText(n){n=Number(n)||0;if(!n)return'';return(n>0?'↑':'↓')+Math.abs(n)+' vs overall';}
function playLine(A,p){var field=A.fieldText?A.fieldText(p):(p.fieldSide+' '+p.yardLine),detail=p.attackDetail&&p.attackDetail!=='NA'?' · '+p.attackDetail:'',cov=resolvedCoverage(p),def=[known(p.front)?display('front',String(p.front)):'',known(cov)?cov:''].filter(Boolean).join(' / ');return'Play '+p.number+' · '+p.quarter+' · '+(A.ord?A.ord(p.down):p.down)+' & '+p.distance+' · '+field+' · '+(p.formation&&p.formation!=='NA'?p.formation+' · ':'')+(def?def+' · ':'')+p.playType+detail+' · '+(Number(p.yards)||0)+' yd';}

function install(A,root){
 if(!A||!root.document||A.__gameIQPro)return A;A.__gameIQPro=true;var d=root.document,detailState=null;
 function $(id){return d.getElementById(id);}function esc(s){return A.esc?A.esc(s):String(s==null?'':s);}
 function injectCss(){if($('gameIQProCss'))return;var l=d.createElement('link');l.id='gameIQProCss';l.rel='stylesheet';l.href='game-iq-pro.css?v=iqpro1';d.head.appendChild(l);}
 function filterLabel(f){var def=defFor(f.key);return(def?def.category:f.key)+': '+display(f.key,String(f.value));}
 function catalog(){var out=[];DEFS.forEach(function(def){valuesFor(A.E,A.state.plays,def).forEach(function(v){out.push({key:def.key,value:String(v),category:def.category,display:display(def.key,String(v)),label:def.category+': '+display(def.key,String(v))});});});return out;}
 function readFilters(){var cat=catalog(),map={};cat.forEach(function(x){map[x.label]=x;});var out=[];d.querySelectorAll('#iqFilterChips .iqFilterChip span').forEach(function(s){var x=map[s.textContent.trim()];if(x)out.push(Object.assign({},x));});return out;}
 function fireFilter(f){var input=$('iqSearchInput');if(!input)return;input.value=filterLabel(f);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));}
 function applyFilters(filters){var clear=$('iqClear');if(clear)clear.click();var i=0;function next(){if(i>=filters.length){setTimeout(function(){var s=$('iqSearchCard');if(s&&s.scrollIntoView)s.scrollIntoView({behavior:'smooth',block:'start'});},70);return;}fireFilter(filters[i++]);setTimeout(next,35);}setTimeout(next,20);}
 function organizeMoreAnalysis(){var metrics=$('metrics'),iq=$('iq');if(!metrics||!iq||$('iqMoreAnalysis'))return;var nodes=[],n=metrics;while(n){nodes.push(n);n=n.nextSibling;}var det=d.createElement('details');det.id='iqMoreAnalysis';det.className='card iqMoreAnalysis';det.innerHTML='<summary><span><strong>More Analysis</strong><small>Run/pass, player production, shell breakdowns and data coverage</small></span><b>Open</b></summary><div id="iqMoreBody" class="iqMoreBody"></div>';metrics.parentNode.insertBefore(det,metrics);var body=det.querySelector('#iqMoreBody');nodes.forEach(function(x){body.appendChild(x);});det.addEventListener('toggle',function(){var b=det.querySelector('summary>b');if(b)b.textContent=det.open?'Close':'Open';});}
 function ensureCoachNow(){var iq=$('iq'),head=iq&&iq.querySelector('.iqhead');if(!iq||!head||$('coachNowCard'))return;var card=d.createElement('div');card.id='coachNowCard';card.className='card coachNowCard';card.innerHTML='<div class="cardhead"><div><div class="eyebrow">COACH NOW</div><h2 class="section">What matters on the next call</h2><p class="muted">Current situation, defensive tendency, offensive answer and what changed.</p></div><span id="coachNowConfidence" class="tinybadge">Waiting</span></div><div id="coachNowGrid" class="coachNowGrid"></div><div class="coachNowFoot"><button id="exploreCurrentIQ" class="btn primary" type="button">Explore current situation</button><div id="iqPins" class="iqPins"></div></div>';head.insertAdjacentElement('afterend',card);$('exploreCurrentIQ').onclick=function(){var c=currentContext();applyFilters(c.filters);};}
 function ensurePinButton(){var card=$('iqSearchCard');if(!card||$('pinIQView'))return;var head=card.querySelector('.cardhead');if(!head)return;var b=d.createElement('button');b.id='pinIQView';b.className='btn smallbtn pinIQView';b.type='button';b.textContent='Pin this question';head.appendChild(b);b.onclick=function(){var fs=readFilters();if(!fs.length)return A.msg&&A.msg('Add a filter before pinning this question');A.state.settings=A.state.settings||{};A.state.settings.iqPins=Array.isArray(A.state.settings.iqPins)?A.state.settings.iqPins:[];var key=pinKey(fs);if(A.state.settings.iqPins.some(function(p){return p.key===key;}))return A.msg&&A.msg('That Game IQ question is already pinned');var name=fs.map(function(f){return f.display;}).join(' + ');A.state.settings.iqPins.push({key:key,name:name,filters:fs.map(function(f){return{key:f.key,value:f.value,category:f.category,display:f.display};})});if(A.state.settings.iqPins.length>8)A.state.settings.iqPins.shift();A.save('iq-pin');renderPins();A.msg&&A.msg('Game IQ question pinned');};}
 function ensureDetail(){var answer=$('iqSearchAnswer');if(!answer||$('iqDetailPanel'))return;var p=d.createElement('div');p.id='iqDetailPanel';p.className='iqDetailPanel hidden';answer.insertAdjacentElement('afterend',p);}
 function ensureUi(){injectCss();ensureCoachNow();ensurePinButton();ensureDetail();organizeMoreAnalysis();installObservers();enhanceRows();renderCoachNow();renderPins();}
 function currentDesired(){var s=A.state.current||{},form=$('formation')&&$('formation').value,hash=$('hash')&&$('hash').value,desired=Number(s.down)===1?[{key:'firstDownSituation',value:firstDownSituation(s.down,s.distance),category:'First down situation',display:display('firstDownSituation',firstDownSituation(s.down,s.distance))}]:[{key:'down',value:String(s.down),category:'Down',display:display('down',String(s.down))},{key:'distanceBucket',value:distanceBucket(s.distance),category:'Distance',display:distanceBucket(s.distance)}];if(known(form))desired.push({key:'formation',value:form,category:'Formation',display:form});var zone=fieldZone(A.E,s);if(zone==='Red Zone'||zone==='Goal To Go')desired.push({key:'fieldZone',value:zone,category:'Field zone',display:zone});if(known(hash))desired.push({key:'hash',value:hash,category:'Hash',display:hash});return desired;}
 function currentContext(){return adaptiveContext(A.E,A.state.plays,currentDesired(),A.isExplosive);}
 function actualCurrentLabel(){var s=A.state.current||{},base=Number(s.down)===1?display('firstDownSituation',firstDownSituation(s.down,s.distance)):(A.ord?A.ord(s.down):s.down)+' & '+distanceBucket(s.distance),parts=[base],form=$('formation')&&$('formation').value,hash=$('hash')&&$('hash').value;if(known(form))parts.push(form);if(known(hash))parts.push(hash+' Hash');return parts.join(' · ');}
 function compareText(key,subset,limit){var rows=compareDistribution(A.E,subset,A.state.plays,key,A.isExplosive).slice(0,limit||2);return rows.length?rows.map(function(r){return'<span><b>'+esc(r.label)+' '+r.share+'%</b>'+(Math.abs(r.delta)>=5?'<em class="'+(r.delta>0?'up':'down')+'">'+esc(deltaText(r.delta))+'</em>':'')+'</span>';}).join(''):'<span class="muted">Not charted yet</span>';}
 function strongestDelta(subset){var candidates=[];['front','coverage'].forEach(function(k){compareDistribution(A.E,subset,A.state.plays,k,A.isExplosive).forEach(function(r){if(Math.abs(r.delta)>=20)candidates.push({label:r.label,current:r.share,delta:r.delta});});});var bl=compareDistribution(A.E,subset,A.state.plays,'blitz',A.isExplosive).find(function(r){return r.value==='Yes';});if(bl&&Math.abs(bl.delta)>=20)candidates.push({label:'Blitz',current:bl.share,delta:bl.delta});return candidates.sort(function(a,b){return Math.abs(b.delta)-Math.abs(a.delta);})[0]||null;}
 function renderCoachNow(){ensureCoachNow();var grid=$('coachNowGrid');if(!grid)return;var c=currentContext(),rows=c.plays,conf=confidence(rows.length),answers=bestAnswers(A.E,rows),delta=strongestDelta(rows),trends=trendSignals(A.E,A.state.plays,A.isExplosive),watch=delta?'<strong>'+esc(delta.label)+' '+delta.current+'%</strong><span>'+esc(deltaText(delta.delta))+'</span>':trends[0]?'<strong>'+esc(trends[0].label)+' '+trends[0].current+'%</strong><span>'+esc(trends[0].window)+' · '+esc(deltaText(trends[0].delta))+'</span>':'<strong>No strong shift yet</strong><span>Keep charting; Game IQ is watching for meaningful change.</span>';var best=answers.best[0]?'<strong>'+esc(answers.best[0].label)+' · '+answers.best[0].ypp.toFixed(1)+' YPP</strong><span>'+answers.best[0].success+'% success · '+answers.best[0].confidence+' confidence</span>':'<strong>No repeated answer yet</strong><span>Needs at least two comparable offensive calls.</span>';grid.innerHTML='<div class="coachNowBlock current"><div class="coachKicker">CURRENT SITUATION</div><h3>'+esc(actualCurrentLabel())+'</h3><div class="coachDefense"><label>Front</label>'+compareText('front',rows,2)+'<label>Coverage</label>'+compareText('coverage',rows,2)+'<label>Blitz</label>'+compareText('blitz',rows,1)+'</div><small>'+(c.broadened?'Broadened to the closest useful sample · ':'')+conf+' confidence</small></div><div class="coachNowBlock"><div class="coachKicker">WHAT\'S WORKING</div>'+best+(answers.best[1]?'<div class="secondaryEdge">Next: '+esc(answers.best[1].label)+' · '+answers.best[1].ypp.toFixed(1)+' YPP</div>':'')+'</div><div class="coachNowBlock"><div class="coachKicker">WATCH THIS</div>'+watch+(trends[0]&&delta?'<div class="secondaryEdge">Trend: '+esc(trends[0].label)+' '+trends[0].current+'% '+esc(trends[0].window)+'</div>':'')+'</div>';$('coachNowConfidence').textContent=rows.length?conf+' confidence':'Waiting';}
 function renderPins(){var box=$('iqPins');if(!box)return;A.state.settings=A.state.settings||{};var pins=Array.isArray(A.state.settings.iqPins)?A.state.settings.iqPins:[];box.innerHTML=pins.length?'<span class="pinLabel">Pinned</span>':'';pins.forEach(function(pin,i){var b=d.createElement('button');b.className='iqPin';b.type='button';b.innerHTML='<span>'+esc(pin.name)+'</span><b aria-label="Remove pin">×</b>';b.onclick=function(e){if(e.target&&e.target.tagName==='B'){e.stopPropagation();A.state.settings.iqPins.splice(i,1);A.save('iq-unpin');renderPins();return;}applyFilters(pin.filters||[]);};box.appendChild(b);});}
 function modeKey(){var b=d.querySelector('#iqShowModes [data-mode].on');return b&&b.dataset.mode||'summary';}
 function rowAddedFilters(label,mode){var out=[],cat=catalog();function exact(key,text){var x=cat.find(function(z){return z.key===key&&z.display===text;});if(x)out.push(x);}if(mode==='frontCoverage'){var m=label.match(/^(.+?) Down \+ (.+)$/);if(m){exact('front',m[1]+' Down');exact('coverage',m[2]);}}else{var map={front:'front',coverage:'coverage',pressure:'pressure',formation:'formation',runType:'runType',conceptFamily:'conceptFamily',concept:'concept',result:'result'};if(map[mode])exact(map[mode],label);}return out;}
 function enhanceRows(){var ans=$('iqSearchAnswer');if(!ans)return;var mode=modeKey(),base=readFilters(),subset=filterPlays(A.E,A.state.plays,base,A.isExplosive);ans.querySelectorAll('.iqResultRow').forEach(function(row){if(row.dataset.iqPro==='1')return;row.dataset.iqPro='1';row.classList.add('iqClickable');var strong=row.querySelector('strong'),label=strong&&strong.textContent.trim();if(!label)return;var added=rowAddedFilters(label,mode);if(added.length){var info=row.querySelector('div span'),detailFilters=mergeFilters(base,added),detailRows=filterPlays(A.E,A.state.plays,detailFilters,A.isExplosive),share=pct(detailRows.length,subset.length),overall=filterPlays(A.E,A.state.plays,added,A.isExplosive),baseShare=pct(overall.length,A.state.plays.length),delta=share-baseShare;if(info&&Math.abs(delta)>=5)info.textContent=info.textContent+' · '+deltaText(delta);var ch=d.createElement('b');ch.className='iqChevron';ch.textContent='›';row.appendChild(ch);row.onclick=function(){openDetail(label,detailFilters,base);};}});}
 function defenseSection(rows){return'<div class="detailDefense"><div><label>Front</label>'+compareTextForRows('front',rows,3)+'</div><div><label>Coverage</label>'+compareTextForRows('coverage',rows,3)+'</div><div><label>Blitz</label>'+compareTextForRows('blitz',rows,2)+'</div><div><label>Blitz type</label>'+compareTextForRows('pressure',rows,3)+'</div><div><label>Safeties</label>'+compareTextForRows('safeties',rows,3)+'</div><div><label>Box</label>'+compareTextForRows('box',rows,3)+'</div></div>';}
 function compareTextForRows(key,rows,limit){var r=compareDistribution(A.E,rows,A.state.plays,key,A.isExplosive).slice(0,limit||3);return r.length?r.map(function(x){return'<span><b>'+esc(x.label)+' '+x.share+'%</b>'+(Math.abs(x.delta)>=5?'<em class="'+(x.delta>0?'up':'down')+'">'+esc(deltaText(x.delta))+'</em>':'')+'</span>';}).join(''):'<span class="muted">Not charted</span>';}
 function filterBreadcrumb(fs){return(fs||[]).map(function(f){return'<span>'+esc(display(f.key,String(f.value)))+'</span>';}).join('');}
 function offenseSection(rows){var s=summary(A.E,rows,A.isExplosive),a=bestAnswers(A.E,rows),best=a.best.map(function(x){return'<div class="answerRow good"><div><strong>'+esc(x.label)+'</strong><span>'+esc(x.kind)+' · '+x.confidence+' confidence</span></div><div><b>'+x.ypp.toFixed(1)+' YPP</b><span>'+x.success+'% success</span></div></div>';}).join('')||'<div class="muted">No repeated offensive answer yet.</div>',worst=a.worst[0]?'<div class="answerRow warn"><div><strong>'+esc(a.worst[0].label)+'</strong><span>Lowest repeated result</span></div><div><b>'+a.worst[0].ypp.toFixed(1)+' YPP</b><span>'+a.worst[0].success+'% success</span></div></div>':'';return'<div class="detailKpis"><div><span>Net YPP</span><b>'+s.ypp.toFixed(1)+'</b></div><div><span>Success</span><b>'+s.success+'%</b></div><div><span>Run</span><b>'+s.runYpp.toFixed(1)+' YPP</b></div><div><span>Pass</span><b>'+s.passYpp.toFixed(1)+' YPP</b></div></div><div class="detailAnswers"><h4>Best observed answers</h4>'+best+(worst?'<h4>Be careful with</h4>'+worst:'')+'</div>';}
 function actualPlays(rows){var a=(rows||[]).slice().reverse().slice(0,10);return a.length?a.map(function(p){return'<div class="detailPlay">'+esc(playLine(A,p))+'</div>';}).join(''):'<div class="muted">No plays in this view.</div>';}
 function renderDetail(){var p=$('iqDetailPanel');if(!p||!detailState)return;var rows=filterPlays(A.E,A.state.plays,detailState.filters,A.isExplosive),suggest=suggestDimensions(A.E,rows,detailState.filters,A.isExplosive);detailState.rows=rows;p.classList.remove('hidden');p.innerHTML='<div class="detailHead"><div><div class="eyebrow">DRILL DOWN</div><h3>'+esc(detailState.title)+'</h3><div class="detailCrumbs">'+filterBreadcrumb(detailState.filters)+'</div></div><div class="detailHeadButtons">'+(detailState.history.length?'<button id="iqDetailBack" class="btn smallbtn">← Back</button>':'')+'<button id="iqDetailClose" class="btn smallbtn">Close</button></div></div><div class="detailGrid"><section><div class="detailSectionHead"><span>WHAT THEY\'RE DOING</span><small>'+confidence(rows.length)+' confidence</small></div>'+defenseSection(rows)+'</section><section><div class="detailSectionHead"><span>HOW WE\'RE DOING</span><small>'+statPlays(A.E,rows).length+' offensive plays</small></div>'+offenseSection(rows)+'</section></div><section class="detailExplore"><div class="detailSectionHead"><span>EXPLORE DEEPER</span><small>Every answer can become the next question.</small></div><div id="detailSplitButtons" class="detailSplitButtons">'+suggest.map(function(x){var def=defFor(x.key);return'<button class="btn smallbtn" data-split="'+esc(x.key)+'">By '+esc(def?def.category:x.key)+'</button>';}).join('')+'</div><div id="iqDetailBreakdown" class="iqDetailBreakdown">'+(suggest[0]?breakdownHtml(suggest[0].key,rows):'<span class="muted">No deeper split available yet.</span>')+'</div></section><section class="detailEvidence"><div class="detailSectionHead"><span>PLAYS IN THIS RESULT</span><small>Raw evidence</small></div>'+actualPlays(rows)+'</section><div class="detailActions"><button id="applyDetailIQ" class="btn primary">Use this exact view in search</button></div>';
 $('iqDetailClose').onclick=closeDetail;if($('iqDetailBack'))$('iqDetailBack').onclick=function(){var prev=detailState.history.pop();if(prev){detailState.filters=prev;renderDetail();}};$('applyDetailIQ').onclick=function(){applyFilters(detailState.filters);closeDetail();};p.querySelectorAll('[data-split]').forEach(function(b){b.onclick=function(){$('iqDetailBreakdown').innerHTML=breakdownHtml(b.dataset.split,rows);wireBreakdown();};});wireBreakdown();p.scrollIntoView({behavior:'smooth',block:'nearest'});}
 function breakdownHtml(key,rows){var r=distribution(A.E,rows,key,A.isExplosive).slice(0,10),def=defFor(key);return'<div class="breakdownTitle">'+esc(def?def.category:key)+'</div>'+r.map(function(x){return'<button class="breakdownRow" data-break-key="'+esc(key)+'" data-break-value="'+esc(x.value)+'"><span><strong>'+esc(x.label)+'</strong><small>'+x.share+'% of this view</small></span><span><b>'+x.ypp.toFixed(1)+' YPP</b><small>'+x.success+'% success</small></span><i>›</i></button>';}).join('');}
 function wireBreakdown(){var box=$('iqDetailBreakdown');if(!box)return;box.querySelectorAll('[data-break-key]').forEach(function(b){b.onclick=function(){var key=b.dataset.breakKey,val=b.dataset.breakValue,def=defFor(key);detailState.history.push(detailState.filters.map(function(f){return Object.assign({},f);}));detailState.filters=mergeFilters(detailState.filters,[{key:key,value:val,category:def?def.category:key,display:display(key,val)}]);detailState.title=display(key,val);renderDetail();};});}
 function openDetail(title,filters,base){ensureDetail();detailState={title:title,filters:filters.map(function(f){return Object.assign({},f);}),base:(base||[]).map(function(f){return Object.assign({},f);}),history:[]};renderDetail();}
 function closeDetail(){var p=$('iqDetailPanel');if(p)p.classList.add('hidden');detailState=null;}
 function installObservers(){var chips=$('iqFilterChips'),ans=$('iqSearchAnswer');if(chips&&!chips.dataset.iqProObserved){chips.dataset.iqProObserved='1';new MutationObserver(function(){setTimeout(function(){renderCoachNow();renderPins();enhanceRows();if(detailState)renderDetail();},0);}).observe(chips,{childList:true,subtree:true});}if(ans&&!ans.dataset.iqProObserved){ans.dataset.iqProObserved='1';new MutationObserver(function(){setTimeout(enhanceRows,0);}).observe(ans,{childList:true,subtree:true});}}
 injectCss();ensureUi();
 var oldIQ=A.renderIQ;if(oldIQ)A.renderIQ=function(){var r=oldIQ.apply(A,arguments);ensureUi();renderCoachNow();renderPins();setTimeout(enhanceRows,0);if(detailState)setTimeout(renderDetail,0);return r;};
 var oldAll=A.renderAll;if(oldAll)A.renderAll=function(){var r=oldAll.apply(A,arguments);renderCoachNow();return r;};
 return A;
}

return{DEFS:DEFS,known:known,distanceBucket:distanceBucket,firstDownSituation:firstDownSituation,resolvedCoverage:resolvedCoverage,valueFor:valueFor,display:display,filterPlays:filterPlays,distribution:distribution,compareDistribution:compareDistribution,confidence:confidence,summary:summary,answerCandidates:answerCandidates,bestAnswers:bestAnswers,adaptiveContext:adaptiveContext,trendSignals:trendSignals,suggestDimensions:suggestDimensions,mergeFilters:mergeFilters,pinKey:pinKey,deltaText:deltaText,install:install};
});
