(function(root,factory){
'use strict';
var C=factory();
if(typeof module==='object'&&module.exports){module.exports=C;return;}
if(root.FNIQ)C.install(root.FNIQ,root);
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function known(v){return v!=null&&v!==''&&v!=='NA'&&v!=='Unknown'&&v!=='Unknown / N/A';}
function pct(a,b){return b?Math.round(a/b*100):0;}
function avg(a){return a.length?a.reduce(function(s,x){return s+x;},0)/a.length:0;}
function sum(a){return a.reduce(function(s,x){return s+x;},0);}
function norm(v){return String(v==null?'':v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function distanceBucket(d){d=Number(d)||10;return d<=3?'Short':d<=7?'Medium':'Long';}
function firstDownSituation(down,distance){down=Number(down);distance=Number(distance);if(down!==1)return null;if(distance===10)return'Ten';if(distance>10)return'Long';if(distance<=3)return'Short';return'Medium';}
function resolvedCoverage(p){var x=p&&p.postCoverage;if(known(x))return x==='Same as pre-snap'?(p.coverage||'NA'):x;return p&&p.coverage||'NA';}
function isBlitz(p){return known(p&&p.pressure)&&p.pressure!=='None';}
function fieldZone(E,p){var a=E.fieldAbs(p.fieldSide,p.yardLine);return a>=90?'Goal To Go':a>=80?'Red Zone':a>=60?'Plus Territory':a>=40?'Midfield':'Own Territory';}
function isTurnover(p){return(p.tags||[]).indexOf('Turnover')>=0||(p.tags||[]).indexOf('Fumble Lost')>=0||p.passResult==='Interception';}
function statPlays(E,plays){return(plays||[]).filter(function(p){if(p.playType!=='Run'&&p.playType!=='Pass')return false;if(p.penalty&&p.penalty.status==='Accepted'&&p.penalty.timing==='DEAD')return false;return true;});}
function schemePlays(E,plays){return statPlays(E,plays).filter(function(p){return!(p.penalty&&p.penalty.status==='Accepted');});}
function explosiveThresholds(settings){settings=settings||{};return{run:Number(settings.explosiveRun)||12,pass:Number(settings.explosivePass)||16};}
function isExplosive(E,p,settings){if(!p||!['Run','Pass'].includes(p.playType))return false;var t=explosiveThresholds(settings);return Number(E.officialNetYards(p))>=(p.playType==='Run'?t.run:t.pass)||(p.tags||[]).indexOf('Explosive')>=0;}
function converted(E,p){if(!p||!(p.down===3||p.down===4))return false;if(isTurnover(p))return false;var n=E.nextSituation(p);return n.reason==='Touchdown'||(!n.possessionEnded&&n.down===1);}
function earnedFirstDown(E,p){if(!p||!['Run','Pass'].includes(p.playType)||isTurnover(p))return false;if(p.penalty&&p.penalty.status==='Accepted'&&p.penalty.timing==='DEAD')return false;var n=E.nextSituation(p);return n.reason==='Touchdown'||(!n.possessionEnded&&n.down===1);}
function conversions(E,plays,down){var rows=statPlays(E,plays).filter(function(p){return Number(p.down)===Number(down);});return{made:rows.filter(function(p){return converted(E,p);}).length,attempts:rows.length,rate:pct(rows.filter(function(p){return converted(E,p);}).length,rows.length)};}
function gameSummary(E,plays,settings){
 var ps=statPlays(E,plays),clean=schemePlays(E,plays),runs=clean.filter(function(p){return p.playType==='Run';}),passSnaps=clean.filter(function(p){return p.playType==='Pass';});
 var attempts=passSnaps.filter(function(p){return['Complete','Incomplete','Interception'].indexOf(p.passResult)>=0;}),completions=attempts.filter(function(p){return p.passResult==='Complete';}),ints=attempts.filter(function(p){return p.passResult==='Interception';}),sacks=passSnaps.filter(function(p){return p.passResult==='Sack';}),passYards=sum(completions.map(function(p){return Number(p.yards)||0;})),rushYards=sum(runs.map(function(p){return Number(p.yards)||0;})),netYards=sum(ps.map(E.officialNetYards)),third=conversions(E,plays,3),fourth=conversions(E,plays,4),pens=(plays||[]).filter(function(p){return p.penalty&&p.penalty.status==='Accepted';}),firsts=ps.filter(function(p){return earnedFirstDown(E,p);}).length,exp=ps.filter(function(p){return isExplosive(E,p,settings);}).length;
 return{plays:ps.length,netYards:netYards,ypp:avg(ps.map(E.officialNetYards)),success:pct(ps.filter(E.success).length,ps.length),firstDowns:firsts,penalties:pens.length,explosives:exp,passing:{completions:completions.length,attempts:attempts.length,yards:passYards,ints:ints.length,sacks:sacks.length,rate:pct(completions.length,attempts.length)},rushing:{carries:runs.length,yards:rushYards,ypc:avg(runs.map(function(p){return Number(p.yards)||0;}))},third:third,fourth:fourth};
}
var DEFS=[
 {key:'firstDownSituation',label:'First down',fixed:['Ten','Long','Medium','Short']},{key:'down',label:'Down',fixed:['1','2','3','4']},{key:'distanceBucket',label:'Distance',fixed:['Short','Medium','Long']},{key:'hash',label:'Hash',fixed:['Left','Middle','Right']},{key:'formation',label:'Formation'},{key:'personnel',label:'Personnel'},{key:'front',label:'Front'},{key:'safeties',label:'High safeties'},{key:'box',label:'Box'},{key:'coverage',label:'Post coverage'},{key:'blitz',label:'Blitz',fixed:['Yes','No']},{key:'pressure',label:'Blitz type'},{key:'playType',label:'Play type',fixed:['Run','Pass']},{key:'runType',label:'Run type'},{key:'passDepth',label:'Pass depth'},{key:'motion',label:'Motion'},{key:'conceptFamily',label:'Concept family'},{key:'concept',label:'Specific concept'},{key:'fieldZone',label:'Field zone',fixed:['Own Territory','Midfield','Plus Territory','Red Zone','Goal To Go']},{key:'quarter',label:'Quarter',fixed:['Q1','Q2','Q3','Q4','OT']},{key:'result',label:'Result',fixed:['Success','Failure','First Down','Explosive','Complete','Incomplete','Interception','Turnover','Penalty']}];
function valueFor(E,p,key){if(key==='firstDownSituation')return firstDownSituation(p.down,p.distance);if(key==='down')return String(p.down);if(key==='distanceBucket')return distanceBucket(p.distance);if(key==='hash')return p.hash;if(key==='formation')return p.formation;if(key==='personnel')return p.personnel;if(key==='front')return String(p.front);if(key==='safeties')return String(p.safeties);if(key==='box')return String(p.box);if(key==='coverage')return resolvedCoverage(p);if(key==='blitz')return isBlitz(p)?'Yes':known(p.pressure)?'No':'Unknown';if(key==='pressure')return p.pressure;if(key==='playType')return p.playType;if(key==='runType')return p.playType==='Run'?p.attackDetail:'NA';if(key==='passDepth')return p.playType==='Pass'?p.attackDetail:'NA';if(key==='motion')return p.motion;if(key==='conceptFamily')return p.conceptFamily;if(key==='concept')return p.concept;if(key==='fieldZone')return fieldZone(E,p);if(key==='quarter')return p.quarter;return null;}
function resultFlags(E,p,settings){var a=[];if(E.success(p))a.push('Success');else if(p.playType==='Run'||p.playType==='Pass')a.push('Failure');if(earnedFirstDown(E,p))a.push('First Down');if(isExplosive(E,p,settings))a.push('Explosive');if(p.passResult==='Complete')a.push('Complete');if(p.passResult==='Incomplete')a.push('Incomplete');if(p.passResult==='Interception')a.push('Interception');if(isTurnover(p))a.push('Turnover');if(p.penalty)a.push('Penalty');return a;}
function display(key,v){if(key==='firstDownSituation')return v==='Ten'?'1st & 10':v==='Long'?'1st & Long':v==='Short'?'1st & Short':'1st & Medium';if(key==='down')return v==='1'?'1st Down':v==='2'?'2nd Down':v==='3'?'3rd Down':'4th Down';if(key==='front')return v+' Down';if(key==='safeties')return v+' High';if(key==='box')return v+' Box';if(key==='blitz')return v==='Yes'?'Blitz':'No Blitz';return v;}
function distinct(plays,fn){var seen={},out=[];(plays||[]).forEach(function(p){var v=fn(p);if(!known(v)||seen[String(v)])return;seen[String(v)]=1;out.push(String(v));});return out.sort();}
function catalog(E,plays,settings){var out=[];DEFS.forEach(function(def){var vals=def.fixed?def.fixed:distinct(plays,function(p){return valueFor(E,p,def.key);});vals.forEach(function(v){if(!known(v))return;var dv=display(def.key,String(v)),aliases=[dv,def.label+' '+dv,v];if(def.key==='down'){if(v==='1')aliases=aliases.concat(['1st','first','first down']);if(v==='2')aliases=aliases.concat(['2nd','second','second down']);if(v==='3')aliases=aliases.concat(['3rd','third','third down']);if(v==='4')aliases=aliases.concat(['4th','fourth','fourth down']);}if(def.key==='firstDownSituation'){aliases=[dv];if(v==='Ten')aliases=aliases.concat(['1st 10','1st and 10','first and 10']);if(v==='Long')aliases=aliases.concat(['1st long','first and long']);if(v==='Medium')aliases=aliases.concat(['1st medium','first and medium']);if(v==='Short')aliases=aliases.concat(['1st short','first and short']);}if(def.key==='blitz'&&v==='Yes')aliases=aliases.concat(['blitz','pressure']);if(def.key==='result'&&v==='Complete')aliases.push('completion');out.push({key:def.key,value:String(v),category:def.label,display:dv,label:def.label+': '+dv,aliases:aliases.map(norm)});});});return out;}
function matches(E,p,f,settings){if(f.key==='result')return resultFlags(E,p,settings).indexOf(f.value)>=0;return String(valueFor(E,p,f.key))===String(f.value);}
function filterPlays(E,plays,filters,settings){return(plays||[]).filter(function(p){return(filters||[]).every(function(f){return matches(E,p,f,settings);});});}
function mergeFilter(filters,f){var out=(filters||[]).map(function(x){return Object.assign({},x);}),i=out.findIndex(function(x){return x.key===f.key;});if(i>=0)out[i]=Object.assign({},f);else out.push(Object.assign({},f));return out;}
function parseQuery(items,q){var text=norm(q),tokens=text.split(/\s+/),ranked=(items||[]).map(function(x){var best=0;x.aliases.forEach(function(a){if(text===a)best=Math.max(best,100+a.length);else if((' '+text+' ').indexOf(' '+a+' ')>=0)best=Math.max(best,70+a.length);else{var w=a.split(/\s+/);if(w.length>1&&w.every(function(z){return tokens.indexOf(z)>=0;}))best=Math.max(best,45+a.length);}});return{x:x,s:best};}).filter(function(z){return z.s>0;}).sort(function(a,b){return b.s-a.s;}),out=[],used={};ranked.forEach(function(z){if(used[z.x.key])return;used[z.x.key]=1;out.push(z.x);});if(out.some(function(x){return x.key==='firstDownSituation';}))out=out.filter(function(x){return x.key!=='down'&&x.key!=='distanceBucket';});return out;}
function groupRows(E,plays,key,settings){var g={};(plays||[]).forEach(function(p){var vals=key==='result'?resultFlags(E,p,settings):[valueFor(E,p,key)];vals.forEach(function(v){if(!known(v)||v==='Unknown')return;(g[String(v)]||(g[String(v)]=[])).push(p);});});var den=(plays||[]).length;return Object.keys(g).map(function(v){var rows=g[v],ps=statPlays(E,rows);return{value:v,label:display(key,v),n:rows.length,share:pct(rows.length,den),ypp:avg(ps.map(E.officialNetYards)),success:pct(ps.filter(E.success).length,ps.length)};}).sort(function(a,b){return b.n-a.n||b.ypp-a.ypp;});}
function workingRows(E,plays){var clean=schemePlays(E,plays),c=[];[{key:'playType',label:'Play type'},{key:'formation',label:'Formation'},{key:'runType',label:'Run type'}].forEach(function(def){var g={};clean.forEach(function(p){var v=valueFor(E,p,def.key);if(known(v))(g[v]||(g[v]=[])).push(p);});Object.keys(g).forEach(function(v){var a=g[v];if(a.length<3)return;c.push({kind:def.label,label:display(def.key,v),n:a.length,ypp:avg(a.map(E.officialNetYards)),success:pct(a.filter(E.success).length,a.length)});});});var ranked=c.slice().sort(function(a,b){return(b.ypp+b.success*.04)-(a.ypp+a.success*.04)||b.n-a.n;});return{best:ranked.slice(0,3),worst:ranked.slice().reverse().slice(0,2)};}
function currentFilters(A){var s=A.state.current||{},out=Number(s.down)===1?[{key:'firstDownSituation',value:firstDownSituation(s.down,s.distance),category:'First down',display:display('firstDownSituation',firstDownSituation(s.down,s.distance))}]:[{key:'down',value:String(s.down),category:'Down',display:display('down',String(s.down))},{key:'distanceBucket',value:distanceBucket(s.distance),category:'Distance',display:distanceBucket(s.distance)}],hash=A.$&&A.$('hash')&&A.$('hash').value,form=A.$&&A.$('formation')&&A.$('formation').value;if(known(hash))out.push({key:'hash',value:hash,category:'Hash',display:hash});if(known(form))out.push({key:'formation',value:form,category:'Formation',display:form});return out;}
function install(A,root){
 if(!A||!root.document||A.__gameIQV3)return A;A.__gameIQV3=true;var d=root.document,state={filters:[],mode:'summary'};
 function $(id){return d.getElementById(id);}function esc(s){return A.esc?A.esc(s):String(s==null?'':s);}
 function injectCss(){if($('gameIQV3Css'))return;var l=d.createElement('link');l.id='gameIQV3Css';l.rel='stylesheet';l.href='game-iq-v3.css?v=iq3';d.head.appendChild(l);}
 function hideLegacy(){['coachNowCard','iqPriorityCard','iqSearchCard','iqSavedViewsCard','iqMoreAnalysis','metrics'].forEach(function(id){var e=$(id);if(e)e.classList.add('iqV3Legacy');});d.querySelectorAll('#iq > .grid2,#iq > .actions,#iq > .card.iqgrid,#iq > details.card.collapsed').forEach(function(e){if(!e.closest('#iqV3Root'))e.classList.add('iqV3Legacy');});}
 function ensureUi(){var iq=$('iq'),head=iq&&iq.querySelector('.iqhead');if(!iq||!head)return;hideLegacy();if($('iqV3Root'))return;var rootEl=d.createElement('div');rootEl.id='iqV3Root';rootEl.innerHTML='<section id="iqV3Scoreboard" class="iq3Card"></section><section class="iq3Card"><div class="iq3Head"><div><div class="eyebrow">COACH ANSWERS</div><h2>One-glance game stats</h2></div><span class="iq3Badge">HEADSET READY</span></div><div id="iq3Stats" class="iq3Stats"></div><div id="iq3Conversions" class="iq3Conversions"></div></section><section class="iq3Grid"><div class="iq3Card"><div class="iq3Head"><div><div class="eyebrow">WHAT\'S WORKING</div><h2>Keep / avoid</h2></div></div><div id="iq3Working"></div></div><div class="iq3Card"><div class="iq3Head"><div><div class="eyebrow">CURRENT SITUATION</div><h2 id="iq3CurrentTitle">Next snap</h2></div></div><div id="iq3Current"></div></div></section><section class="iq3Card"><div class="iq3Head"><div><div class="eyebrow">COACH SHORTCUTS</div><h2>One tap to the question</h2></div></div><div id="iq3Shortcuts" class="iq3Shortcuts"></div></section><section class="iq3Card"><div class="iq3Head"><div><div class="eyebrow">ASK GAME IQ</div><h2>Filter without surprises</h2><p>Every control writes to one filter state. The screen never guesses an extra filter.</p></div><span id="iq3Count" class="iq3Badge">0 plays</span></div><div class="iq3Search"><input id="iq3SearchInput" placeholder="Try: 3rd short left hash blitz pass"><button id="iq3SearchGo" class="btn primary">Add filters</button><button id="iq3Clear" class="btn">Clear</button></div><div id="iq3Chips" class="iq3Chips"></div><div id="iq3Facets" class="iq3Facets"></div><details class="iq3MoreFilters"><summary>More filters</summary><div id="iq3MoreFacets" class="iq3Facets"></div></details><div class="iq3Mode"><span>Show</span><select id="iq3Mode"><option value="summary">Summary</option><option value="frontCoverage">Front + Coverage</option><option value="front">Front</option><option value="coverage">Coverage</option><option value="formation">Formation</option><option value="blitz">Blitz</option><option value="playType">Play Type</option><option value="result">Results</option><option value="plays">Actual plays</option></select><button id="iq3SaveView" class="btn">Save for quick access</button></div><div id="iq3Answer"></div><div id="iq3Saved" class="iq3Saved"></div></section><details class="iq3Card iq3More"><summary><span><strong>More Analysis</strong><small>Explosives, data coverage and deeper production</small></span><b>Open</b></summary><div id="iq3MoreBody"></div></details>';
 head.insertAdjacentElement('afterend',rootEl);wire();
 }
 function filterItem(key,value){var c=catalog(A.E,A.state.plays,A.state.settings||{});return c.find(function(x){return x.key===key&&String(x.value)===String(value);})||{key:key,value:String(value),category:(DEFS.find(function(d){return d.key===key;})||{}).label||key,display:display(key,String(value))};}
 function setFilters(fs){state.filters=[];(fs||[]).forEach(function(f){state.filters=mergeFilter(state.filters,filterItem(f.key,f.value));});render();}
 function addFilter(f){if(f.key==='firstDownSituation')state.filters=state.filters.filter(function(x){return x.key!=='down'&&x.key!=='distanceBucket';});else if(f.key==='down'||f.key==='distanceBucket')state.filters=state.filters.filter(function(x){return x.key!=='firstDownSituation';});state.filters=mergeFilter(state.filters,f);render();}
 function removeFilter(key){state.filters=state.filters.filter(function(f){return f.key!==key;});render();}
 A.getIQFilters=function(){return state.filters.map(function(f){return Object.assign({},f);});};A.setIQFilters=setFilters;
 function facetSelect(def,host){var s=d.createElement('select');s.dataset.iq3Key=def.key;s.innerHTML='<option value="">'+esc(def.label)+'</option>';var vals=def.fixed?def.fixed:distinct(A.state.plays,function(p){return valueFor(A.E,p,def.key);});vals.forEach(function(v){if(!known(v))return;var o=d.createElement('option');o.value=String(v);o.textContent=display(def.key,String(v));s.appendChild(o);});var cur=state.filters.find(function(f){return f.key===def.key;});s.value=cur?cur.value:'';s.onchange=function(){if(!this.value)removeFilter(def.key);else addFilter(filterItem(def.key,this.value));};host.appendChild(s);}
 function renderFacets(){var main=$('iq3Facets'),more=$('iq3MoreFacets');if(!main||!more)return;main.innerHTML='';more.innerHTML='';['firstDownSituation','down','distanceBucket','hash','formation','front','coverage','blitz','playType','result'].forEach(function(k){facetSelect(DEFS.find(function(x){return x.key===k;}),main);});['personnel','safeties','box','pressure','runType','passDepth','motion','conceptFamily','concept','fieldZone','quarter'].forEach(function(k){facetSelect(DEFS.find(function(x){return x.key===k;}),more);});}
 function renderChips(){var box=$('iq3Chips');if(!box)return;box.innerHTML='';state.filters.forEach(function(f){var b=d.createElement('button');b.type='button';b.className='iq3Chip';b.innerHTML='<span>'+esc(f.display)+'</span><b>×</b>';b.onclick=function(){removeFilter(f.key);};box.appendChild(b);});}
 function search(){var q=$('iq3SearchInput').value.trim();if(!q)return;var parsed=parseQuery(catalog(A.E,A.state.plays,A.state.settings||{}),q);parsed.forEach(function(f){state.filters=mergeFilter(state.filters,f);});$('iq3SearchInput').value='';render();}
 function summaryCards(s){return'<div class="iq3Stat hero"><span>Total Plays</span><b>'+s.plays+'</b><small>'+s.netYards+' net yards</small></div><div class="iq3Stat"><span>YPP</span><b>'+s.ypp.toFixed(1)+'</b><small>net yards / play</small></div><div class="iq3Stat '+(s.success>=50?'good':'bad')+'"><span>Success</span><b>'+s.success+'%</b><small>50% on 1st/2nd · convert 3rd/4th</small></div><div class="iq3Stat"><span>First Downs</span><b>'+s.firstDowns+'</b><small>earned</small></div><div class="iq3Stat"><span>Penalties</span><b>'+s.penalties+'</b><small>accepted</small></div><div class="iq3Stat"><span>Explosives</span><b>'+s.explosives+'</b><small>configured thresholds</small></div>';}
 function renderHeadline(){var s=gameSummary(A.E,A.state.plays,A.state.settings||{}),box=$('iq3Stats');if(!box)return;box.innerHTML=summaryCards(s)+'<div class="iq3StatGroup pass"><div><span>PASSING</span><b>'+s.passing.completions+' / '+s.passing.attempts+'</b><small>'+s.passing.yards+' yards · '+s.passing.ints+' INT · '+s.passing.sacks+' sacks</small></div></div><div class="iq3StatGroup rush"><div><span>RUSHING</span><b>'+s.rushing.carries+' carries</b><small>'+s.rushing.yards+' yards · '+s.rushing.ypc.toFixed(1)+' YPC</small></div></div>';$('iq3Conversions').innerHTML='<div class="iq3Conversion '+(s.third.rate>=50?'good':'bad')+'"><span>3RD DOWN</span><b>'+s.third.made+' / '+s.third.attempts+' · '+s.third.rate+'%</b><small>conversion rate</small></div><div class="iq3Conversion '+(s.fourth.rate>=50?'good':'bad')+'"><span>4TH DOWN</span><b>'+s.fourth.made+' / '+s.fourth.attempts+' · '+s.fourth.rate+'%</b><small>conversion rate</small></div>';}
 function renderWorking(){var w=workingRows(A.E,A.state.plays),box=$('iq3Working');if(!box)return;var h='';w.best.slice(0,2).forEach(function(x){h+='<div class="iq3Edge good"><span><strong>'+esc(x.label)+'</strong><small>'+esc(x.kind)+' · '+x.n+' plays</small></span><span><b>'+x.ypp.toFixed(1)+' YPP</b><small>'+x.success+'% success</small></span></div>';});w.worst.slice(0,1).forEach(function(x){h+='<div class="iq3Edge bad"><span><strong>'+esc(x.label)+'</strong><small>lowest repeated result · '+x.n+' plays</small></span><span><b>'+x.ypp.toFixed(1)+' YPP</b><small>'+x.success+'% success</small></span></div>';});box.innerHTML=h||'<div class="iq3Empty">Need at least three comparable calls before FNIQ labels something working or not working.</div>';}
 function topText(rows){return rows.length?rows.slice(0,2).map(function(r){return r.label+' '+r.share+'%';}).join(' · '):'Not charted';}
 function renderCurrent(){var fs=currentFilters(A),rows=filterPlays(A.E,A.state.plays,fs,A.state.settings||{}),title=fs.map(function(f){return f.display;}).join(' · ');$('iq3CurrentTitle').textContent=title||'Next snap';var ps=statPlays(A.E,rows),front=groupRows(A.E,rows,'front',A.state.settings||{}),cov=groupRows(A.E,rows,'coverage',A.state.settings||{}),bl=groupRows(A.E,rows,'blitz',A.state.settings||{});$('iq3Current').innerHTML='<div class="iq3CurrentLine"><span>Sample</span><b>'+ps.length+' plays</b></div><div class="iq3CurrentLine"><span>Front</span><b>'+esc(topText(front))+'</b></div><div class="iq3CurrentLine"><span>Coverage</span><b>'+esc(topText(cov))+'</b></div><div class="iq3CurrentLine"><span>Blitz</span><b>'+esc(topText(bl))+'</b></div>'+(ps.length?'<div class="iq3CurrentKpi"><b>'+avg(ps.map(A.E.officialNetYards)).toFixed(1)+' YPP</b><span>'+pct(ps.filter(A.E.success).length,ps.length)+'% success</span></div>':'');}
 function renderShortcuts(){var box=$('iq3Shortcuts');if(!box)return;var defs=[['1st & 10',[['firstDownSituation','Ten']]],['1st & Long',[['firstDownSituation','Long']]],['2nd & Short',[['down','2'],['distanceBucket','Short']]],['2nd & Medium',[['down','2'],['distanceBucket','Medium']]],['2nd & Long',[['down','2'],['distanceBucket','Long']]],['3rd & Short',[['down','3'],['distanceBucket','Short']]],['3rd & Medium',[['down','3'],['distanceBucket','Medium']]],['3rd & Long',[['down','3'],['distanceBucket','Long']]],['Red Zone',[['fieldZone','Red Zone']]]];box.innerHTML='';defs.forEach(function(x){var b=d.createElement('button');b.type='button';b.textContent=x[0];b.onclick=function(){setFilters(x[1].map(function(z){return filterItem(z[0],z[1]);}));$('iq3Answer').scrollIntoView({block:'nearest'});};box.appendChild(b);});}
 function frontCoverage(rows){var g={};rows.forEach(function(p){var f=known(p.front)?display('front',String(p.front)):'Unknown',c=known(resolvedCoverage(p))?resolvedCoverage(p):'Unknown',k=f+' + '+c;(g[k]||(g[k]=[])).push(p);});return Object.keys(g).map(function(k){var a=g[k],ps=statPlays(A.E,a);return{label:k,n:a.length,share:pct(a.length,rows.length),ypp:avg(ps.map(A.E.officialNetYards)),success:pct(ps.filter(A.E.success).length,ps.length)};}).sort(function(a,b){return b.n-a.n;});}
 function resultRows(rows){if(state.mode==='frontCoverage')return frontCoverage(rows);if(['front','coverage','formation','blitz','playType','result'].indexOf(state.mode)>=0)return groupRows(A.E,rows,state.mode,A.state.settings||{});return[];}
 function renderAnswer(){var rows=filterPlays(A.E,A.state.plays,state.filters,A.state.settings||{}),ps=statPlays(A.E,rows),box=$('iq3Answer');$('iq3Count').textContent=ps.length+' play'+(ps.length===1?'':'s');if(state.mode==='summary'){var s=gameSummary(A.E,rows,A.state.settings||{});box.innerHTML='<div class="iq3AnswerSummary"><div><span>Net YPP</span><b>'+s.ypp.toFixed(1)+'</b></div><div><span>Success</span><b>'+s.success+'%</b></div><div><span>Run / Pass</span><b>'+s.rushing.carries+' / '+s.passing.attempts+'</b></div><div><span>3rd Down</span><b>'+s.third.made+'/'+s.third.attempts+' · '+s.third.rate+'%</b></div><div><span>Explosives</span><b>'+s.explosives+'</b></div></div>';return;}if(state.mode==='plays'){box.innerHTML=rows.length?rows.slice().reverse().slice(0,30).map(function(p){return'<div class="iq3Play"><strong>Play '+p.number+'</strong><span>'+esc(p.quarter+' · '+(A.ord?A.ord(p.down):p.down)+' & '+p.distance+' · '+(A.fieldText?A.fieldText(p):p.fieldSide+' '+p.yardLine))+'</span><b>'+esc(p.playType+(p.passResult?' '+p.passResult:'')+' · '+(Number(p.yards)||0)+' yd')+'</b></div>';}).join(''):'<div class="iq3Empty">No plays match.</div>';return;}var rr=resultRows(rows);box.innerHTML=rr.length?rr.slice(0,20).map(function(r){return'<div class="iq3ResultRow"><span><strong>'+esc(r.label)+'</strong><small>'+r.n+' plays · '+r.share+'%</small></span><span><b>'+r.ypp.toFixed(1)+' YPP</b><small>'+r.success+'% success</small></span></div>';}).join(''):'<div class="iq3Empty">No plays match this view.</div>';}
 function renderSaved(){var box=$('iq3Saved');if(!box)return;A.state.settings=A.state.settings||{};var pins=Array.isArray(A.state.settings.iqPins)?A.state.settings.iqPins:[];box.innerHTML=pins.length?'<div class="iq3SavedLabel">SAVED VIEWS</div>':'';pins.forEach(function(pin,i){var b=d.createElement('button');b.type='button';b.className='iq3SavedView';b.innerHTML='<span>'+esc(pin.name)+'</span><b>×</b>';b.onclick=function(e){if(e.target.tagName==='B'){A.state.settings.iqPins.splice(i,1);A.save('iq-unpin');renderSaved();return;}setFilters(pin.filters||[]);};box.appendChild(b);});}
 function saveView(){if(!state.filters.length)return A.msg&&A.msg('Add a filter before saving this view');A.state.settings=A.state.settings||{};A.state.settings.iqPins=Array.isArray(A.state.settings.iqPins)?A.state.settings.iqPins:[];var key=state.filters.map(function(f){return f.key+'='+f.value;}).sort().join('|');if(A.state.settings.iqPins.some(function(p){return p.key===key;}))return A.msg&&A.msg('That view is already saved');var name=state.filters.map(function(f){return f.display;}).join(' + ');A.state.settings.iqPins.push({key:key,name:name,filters:state.filters.map(function(f){return{key:f.key,value:f.value,category:f.category,display:f.display};})});if(A.state.settings.iqPins.length>8)A.state.settings.iqPins.shift();A.save('iq-pin');renderSaved();A.msg&&A.msg('Saved for quick access');}
 function coverageStats(){var plays=A.state.plays||[],fields=[['Hash',function(p){return p.hash;}],['Formation',function(p){return p.formation;}],['Front',function(p){return p.front;}],['Safeties',function(p){return p.safeties;}],['Coverage',resolvedCoverage],['Blitz',function(p){return p.pressure;}],['Player',function(p){return p.player;}],['Run/Pass detail',function(p){return p.attackDetail;}]],n=plays.length;return fields.map(function(x){var k=plays.filter(function(p){return known(x[1](p));}).length;return{x:x[0],known:k,rate:pct(k,n)};});}
 function renderMore(){var s=gameSummary(A.E,A.state.plays,A.state.settings||{}),t=explosiveThresholds(A.state.settings||{}),q=coverageStats(),box=$('iq3MoreBody');if(!box)return;box.innerHTML='<div class="iq3MoreMetrics"><div><span>Explosives</span><b>'+s.explosives+'</b><small>Run '+t.run+'+ · Pass '+t.pass+'+</small></div><div><span>Pass completion</span><b>'+s.passing.rate+'%</b><small>'+s.passing.completions+'/'+s.passing.attempts+'</small></div><div><span>Rush YPC</span><b>'+s.rushing.ypc.toFixed(1)+'</b><small>'+s.rushing.carries+' carries</small></div></div><div class="iq3SuccessDef"><strong>Success definition</strong><span>1st & 2nd: gain at least 50% of yards needed. 3rd & 4th: convert the first down or score.</span></div><div class="iq3Coverage">'+q.map(function(x){return'<div><span>'+x.x+'</span><b>'+x.rate+'%</b><small>'+x.known+'/'+A.state.plays.length+'</small></div>';}).join('')+'</div>';}
 function wire(){if($('iq3SearchGo'))$('iq3SearchGo').onclick=search;if($('iq3SearchInput'))$('iq3SearchInput').onkeydown=function(e){if(e.key==='Enter'){e.preventDefault();search();}};if($('iq3Clear'))$('iq3Clear').onclick=function(){state.filters=[];render();};if($('iq3Mode'))$('iq3Mode').onchange=function(){state.mode=this.value;renderAnswer();};if($('iq3SaveView'))$('iq3SaveView').onclick=saveView;}
 function render(){ensureUi();hideLegacy();renderHeadline();renderWorking();renderCurrent();renderShortcuts();renderChips();renderFacets();renderAnswer();renderSaved();renderMore();}
 injectCss();ensureUi();A.renderIQ=render;render();return A;
}
return{known:known,distanceBucket:distanceBucket,firstDownSituation:firstDownSituation,resolvedCoverage:resolvedCoverage,isBlitz:isBlitz,statPlays:statPlays,schemePlays:schemePlays,explosiveThresholds:explosiveThresholds,isExplosive:isExplosive,converted:converted,earnedFirstDown:earnedFirstDown,conversions:conversions,gameSummary:gameSummary,valueFor:valueFor,resultFlags:resultFlags,catalog:catalog,filterPlays:filterPlays,mergeFilter:mergeFilter,parseQuery:parseQuery,groupRows:groupRows,workingRows:workingRows,fieldZone:fieldZone,install:install};
});
