(function(root,factory){
'use strict';
var C=factory();
if(typeof module==='object'&&module.exports){module.exports=C;return;}
if(root.FNIQ)C.install(root.FNIQ,root);
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function num(v,d){var n=Number(v);return Number.isFinite(n)?n:d;}
function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
function spotAbs(side,yard){if(side==='GOAL')return 100;if(side==='50')return 50;return side==='OWN'?num(yard,25):100-num(yard,25);}
function spotFromAbs(a){a=clamp(Math.round(num(a,25)),1,100);if(a>=100)return{fieldSide:'GOAL',yardLine:0,label:'Goal line'};if(a===50)return{fieldSide:'50',yardLine:50,label:'50'};if(a<50)return{fieldSide:'OWN',yardLine:a,label:'Own '+a};return{fieldSide:'OPP',yardLine:100-a,label:'Opp '+(100-a)};}
function yardsBetween(startSide,startYard,endSide,endYard){return Math.round(spotAbs(endSide,endYard)-spotAbs(startSide,startYard));}
function endFromYards(startSide,startYard,yards){return spotFromAbs(spotAbs(startSide,startYard)+num(yards,0));}
function cloneScore(s){return{us:Number(s&&s.us)||0,them:Number(s&&s.them)||0};}
function opponentPoints(p){return Math.max(0,Number(p&&p.opponentPoints)||0);}
function ensureTag(p,t){p.tags=Array.isArray(p.tags)?p.tags:[];if(p.tags.indexOf(t)<0)p.tags.push(t);}
function removeTag(p,t){p.tags=Array.isArray(p.tags)?p.tags:[];p.tags=p.tags.filter(function(x){return x!==t;});}
function buildOfficialNext(E,p,x){
 if(!x||!x.fieldSide)return null;
 var side=x.fieldSide,y=side==='50'?50:Number(x.yardLine),down=Number(x.down),distance=Number(x.distance);
 if(!Number.isFinite(down)||down<1||down>4||!Number.isFinite(distance)||distance<1)return null;
 if(side!=='50'&&(!Number.isFinite(y)||y<1||y>49))return null;
 var s=E.normalizeSituation({quarter:x.quarter||p.quarter,down:down,distance:distance,fieldSide:side,yardLine:y});
 return{quarter:s.quarter,down:s.down,distance:s.distance,fieldSide:s.fieldSide,yardLine:s.yardLine,drive:p.drive,possessionEnded:false,reason:'Official next snap'};
}
function install(A,root){
 if(!A||!root.document||A.__gameDay3)return A;A.__gameDay3=true;
 var d=root.document,guard=false;
 function $(id){return d.getElementById(id);}
 function fire(el,type){if(el)el.dispatchEvent(new Event(type||'change',{bubbles:true}));}
 function injectCss(){if($('gameDay3Css'))return;var l=d.createElement('link');l.id='gameDay3Css';l.rel='stylesheet';l.href='game-day-3.css?v=gd3';d.head.appendChild(l);}
 function move(el,host){if(el&&host&&el.parentNode!==host)host.appendChild(el);}
 function wrap(id){var e=$(id);return e&&e.parentElement;}
 function option(select,value,label){if(!select)return;if(![].some.call(select.options,function(o){return o.value===value;})){var o=d.createElement('option');o.value=value;o.textContent=label||value;select.appendChild(o);}}
 function ensureMarkup(){
  var main=d.querySelector('#live main');if(!main||$('gd3Tracker'))return;
  var card=d.createElement('section');card.id='gd3Tracker';card.className='card gd3Tracker';
  card.innerHTML='<div class="gd3Top"><div><div class="eyebrow">SPEED TRACKER</div><h2>Chart the snap. Never do yardage math.</h2></div><div class="gd3Target">HURRY-UP READY</div></div>'+
   '<div class="gd3Situation" id="gd3Situation"></div>'+
   '<div class="gd3Section"><div class="gd3SectionLabel">PRE-SNAP</div><div class="gd3Pre"><div class="gd3Field gd3Hash"><label>Hash</label><div id="gd3HashButtons" class="gd3Quick"></div></div><div id="gd3FormationHost" class="gd3Field"></div><div id="gd3PersonnelHost" class="gd3Field"></div></div></div>'+
   '<div class="gd3Section"><div class="gd3SectionLabel">DEFENSIVE PICTURE</div><div class="gd3Defense"><div id="gd3FrontHost"></div><div id="gd3SafetyHost"></div><div id="gd3CoverageHost"></div></div></div>'+
   '<div class="gd3Section gd3ResultSection"><div class="gd3SectionLabel">SNAP RESULT</div><div id="gd3PlayTypeHost"></div><div id="gd3PassResult"></div><div id="gd3PlayResultCore" class="gd3PlayResultCore"><div class="gd3Spot"><label>Where is the ball now?</label><div class="gd3SpotInputs"><select id="gd3EndSide"><option value="OWN">Own</option><option value="50">50</option><option value="OPP">Opp</option><option value="GOAL">Goal line</option></select><input id="gd3EndYard" type="number" min="1" max="49"><button id="gd3Goal" class="btn gd3Goal" type="button">TD / Goal line</button></div><div id="gd3Gain" class="gd3Gain">+0 yards</div></div><div id="gd3YardsHost"></div><div class="gd3Field"><label>Blitz</label><div id="gd3BlitzButtons" class="gd3Quick"></div></div><div class="gd3Field"><label>Post coverage</label><div id="gd3CoverageButtons" class="gd3Quick gd3CoverQuick"></div></div></div><div id="gd3TurnoverExtra" class="gd3TurnoverExtra hidden"><button id="gd3PickSix" class="gd3DangerChoice" type="button">Pick Six / INT returned for TD</button></div><button id="gd3PenaltyToggle" class="gd3PenaltyToggle" type="button">+ Penalty on this play</button></div>'+
   '<div id="gd3PenaltyPanel" class="gd3PenaltyPanel hidden"><div class="gd3PenaltyHead"><strong>Penalty</strong><span>Enter what the officials announce. FNIQ handles the state.</span></div><div class="gd3PenaltyQuick"><div><label>Penalty</label><select id="gd3PenType"><option value="">Choose</option><option>False Start</option><option>Holding</option><option>Offside</option><option>Encroachment</option><option>Pass Interference</option><option>Personal Foul</option><option>Unsportsmanlike Conduct</option><option>Illegal Formation</option><option>Illegal Motion</option><option>Delay of Game</option><option>Other</option></select></div><div><label>On</label><select id="gd3PenTeam"><option value="">Choose</option><option>Offense</option><option>Defense</option></select></div><div><label>Status</label><select id="gd3PenStatus"><option>Accepted</option><option>Declined</option><option>Offsetting</option></select></div><div><label>When?</label><select id="gd3PenTiming"><option value="DEAD">No snap / dead ball</option><option value="LIVE">Play happened</option><option value="POST">After play</option></select></div></div><div id="gd3OfficialNext" class="gd3OfficialNext"><div class="gd3OfficialTitle">OFFICIAL NEXT SNAP</div><div class="gd3OfficialGrid"><select id="gd3NextDown"><option value="1">1st</option><option value="2">2nd</option><option value="3">3rd</option><option value="4">4th</option></select><input id="gd3NextDistance" type="number" min="1" placeholder="Distance"><select id="gd3NextSide"><option value="OWN">Own</option><option value="50">50</option><option value="OPP">Opp</option></select><input id="gd3NextYard" type="number" min="1" max="49" placeholder="Yard"></div><div class="gd3PenaltyHint">No enforcement math. Enter the down, distance and spot shown by the officials.</div></div></div>'+
   '<details id="gd3Optional" class="gd3Optional"><summary>Optional detail <span>player • motion • box • blitz type • concepts</span></summary><div id="gd3OptionalBody" class="gd3OptionalBody"></div></details>'+
   '<div class="gd3Bottom"><div id="gd3SpeedHealth" class="gd3SpeedHealth">Choose Run, Pass, or Penalty</div><div id="gd3Actions" class="gd3Actions"></div></div>';
  var fast=main.querySelector('.fastbar');if(fast)fast.insertAdjacentElement('afterend',card);else main.insertBefore(card,main.firstChild);
  var situation=$('gd3Situation');['quarter','down','distance','side'].forEach(function(id){move(wrap(id),situation);});var yardWrap=wrap('yard');if(yardWrap&&yardWrap.parentElement&&yardWrap.parentElement.classList.contains('fieldinputs')){move(yardWrap.parentElement.parentElement,situation);}else move(yardWrap,situation);
  move(wrap('formation'),$('gd3FormationHost'));move(wrap('personnel'),$('gd3PersonnelHost'));
  var fw=d.querySelector('[data-group="front"]');move(fw&&fw.parentElement,$('gd3FrontHost'));var sw=d.querySelector('[data-group="safeties"]');move(sw&&sw.parentElement,$('gd3SafetyHost'));move(wrap('coverage'),$('gd3CoverageHost'));
  var pt=d.querySelector('[data-group="playType"]');move(pt,$('gd3PlayTypeHost'));var noPlay=pt&&pt.querySelector('[data-v="No Play"]');if(noPlay)noPlay.remove();
  move($('passArea'),$('gd3PassResult'));
  var yards=$('yards');if(yards)move(yards.parentElement.parentElement,$('gd3YardsHost'));
  var opt=$('gd3OptionalBody');var box=d.querySelector('[data-group="box"]');move(box&&box.parentElement,opt);move(wrap('motion'),opt);move(wrap('pressure'),opt);move(wrap('postCoverage'),opt);move($('detail'),opt);move(wrap('concept'),opt);move(wrap('direction'),opt);move(wrap('notes'),opt);var tagwrap=d.querySelector('.tagwrap');move(tagwrap&&tagwrap.parentElement,opt);
  var actions=$('gd3Actions');['editLast','cancelEditLast','undo','save'].forEach(function(id){move($(id),actions);});
  d.querySelectorAll('#live .stepcard').forEach(function(x){x.classList.add('gd3LegacyHidden');});var pen=$('penaltyPanel');if(pen)pen.classList.add('gd3LegacyPenalty');var es=d.querySelector('.entrysummary');if(es)es.classList.add('gd3LegacyHidden');var sr=d.querySelector('.safetyrow');if(sr)sr.classList.add('gd3LegacyShell');
  buildHashButtons();buildBlitzButtons();buildCoverageButtons();wireSpeed();syncSpotFromYards();syncQuickStates();updatePenaltyVisibility();updateSpeedHealth();
 }
 function buildHashButtons(){var h=$('gd3HashButtons');if(!h||h.children.length)return;[['Left','L'],['Middle','M'],['Right','R'],['NA','?']].forEach(function(x){var b=d.createElement('button');b.type='button';b.dataset.hash=x[0];b.textContent=x[1];b.onclick=function(){$('hash').value=x[0];fire($('hash'));syncHashButtons();};h.appendChild(b);});syncHashButtons();}
 function syncHashButtons(){var v=$('hash')&&$('hash').value;$('gd3HashButtons')&&$('gd3HashButtons').querySelectorAll('button').forEach(function(b){b.classList.toggle('on',b.dataset.hash===v);});}
 function buildBlitzButtons(){var h=$('gd3BlitzButtons');if(!h||h.children.length)return;[['Other','BLITZ'],['None','NO'],['NA','?']].forEach(function(x){var b=d.createElement('button');b.type='button';b.dataset.pressure=x[0];b.textContent=x[1];b.onclick=function(){$('pressure').value=x[0];fire($('pressure'));syncBlitzButtons();};h.appendChild(b);});}
 function syncBlitzButtons(){var v=$('pressure')&&$('pressure').value,kind=v==='NA'?'NA':v==='None'?'None':'Other';$('gd3BlitzButtons')&&$('gd3BlitzButtons').querySelectorAll('button').forEach(function(b){b.classList.toggle('on',b.dataset.pressure===kind);});}
 function buildCoverageButtons(){var h=$('gd3CoverageButtons');if(!h||h.children.length)return;[['Same as pre-snap','SAME'],['Cover 1','C1'],['Cover 2','C2'],['Cover 3','C3'],['Cover 4','C4'],['Other','OTHER'],['NA','?']].forEach(function(x){var b=d.createElement('button');b.type='button';b.dataset.coverage=x[0];b.textContent=x[1];b.onclick=function(){option($('postCoverage'),x[0],x[0]);$('postCoverage').value=x[0];fire($('postCoverage'));syncCoverageButtons();};h.appendChild(b);});}
 function syncCoverageButtons(){var v=$('postCoverage')&&$('postCoverage').value;$('gd3CoverageButtons')&&$('gd3CoverageButtons').querySelectorAll('button').forEach(function(b){b.classList.toggle('on',b.dataset.coverage===v);});}
 function currentStart(){var s=A.readSituation?A.readSituation():A.state.current;return{fieldSide:s.fieldSide,yardLine:s.yardLine};}
 function setEndControls(spot){var side=$('gd3EndSide'),yard=$('gd3EndYard');if(!side||!yard)return;side.value=spot.fieldSide;yard.disabled=spot.fieldSide==='50'||spot.fieldSide==='GOAL';yard.value=spot.fieldSide==='50'?'50':spot.fieldSide==='GOAL'?'':spot.yardLine;}
 function syncSpotFromYards(){if(guard)return;guard=true;var s=currentStart(),spot=endFromYards(s.fieldSide,s.yardLine,Number($('yards')&&$('yards').value)||0);setEndControls(spot);renderGain();guard=false;}
 function syncYardsFromSpot(){if(guard)return;var side=$('gd3EndSide').value,y=side==='50'?50:side==='GOAL'?0:Number($('gd3EndYard').value);if(side!=='50'&&side!=='GOAL'&&(!Number.isFinite(y)||y<1||y>49))return;guard=true;var s=currentStart(),gain=yardsBetween(s.fieldSide,s.yardLine,side,y);$('yards').value=String(gain);fire($('yards'),'input');if(side==='GOAL')setTag('Touchdown',true);renderGain();guard=false;}
 function renderGain(){var y=Number($('yards')&&$('yards').value)||0,g=$('gd3Gain');if(g)g.textContent=(y>=0?'+':'')+y+' yards';}
 function setTag(tag,on){var b=d.querySelector('.tag[data-tag="'+tag+'"]');if(b)b.classList.toggle('on',!!on);}
 function penaltyTagged(){var b=d.querySelector('.tag[data-tag="Penalty"]');return !!(b&&b.classList.contains('on'));}
 function setPenaltyTagged(on){var b=d.querySelector('.tag[data-tag="Penalty"]');if(b)b.classList.toggle('on',!!on);}
 function syncPenaltyLegacy(){
  var map=[['gd3PenType','penType'],['gd3PenTeam','penTeam'],['gd3PenStatus','penStatus'],['gd3PenTiming','penTiming']];map.forEach(function(x){if($(x[0])&&$(x[1]))$(x[1]).value=$(x[0]).value;});
  if($('penDistance'))$('penDistance').value=0;var op=null;if($('gd3NextDown')){var ss=A.state.current||{},ns=$('gd3NextSide')&&$('gd3NextSide').value,ny=ns==='50'?50:Number($('gd3NextYard')&&$('gd3NextYard').value);if(ns&&(ns==='50'||(Number.isFinite(ny)&&ny>=1&&ny<=49)))op=Math.round(A.E.fieldAbs(ns,ny)-A.E.fieldAbs(ss.fieldSide,ss.yardLine));}if($('penNetOverride'))$('penNetOverride').value=op==null?'':String(op);if($('penYards'))$('penYards').value=op==null?0:op;if($('penEffect'))$('penEffect').value=$('gd3PenTiming')&&$('gd3PenTiming').value==='DEAD'?'REPEAT':'COUNT';
 }
 function presetNext(){var s=A.state.current||{};if(!$('gd3NextDown'))return;$('gd3NextDown').value=String(s.down||1);$('gd3NextDistance').value=String(s.distance||10);$('gd3NextSide').value=s.fieldSide||'OWN';$('gd3NextYard').disabled=s.fieldSide==='50';$('gd3NextYard').value=s.fieldSide==='50'?'50':String(s.yardLine||25);}
 function updatePenaltyVisibility(){var dead=A.sel&&A.sel.playType==='Penalty',on=dead||penaltyTagged(),p=$('gd3PenaltyPanel');if(p)p.classList.toggle('hidden',!on);if($('gd3PenaltyToggle'))$('gd3PenaltyToggle').classList.toggle('on',penaltyTagged());if($('gd3PlayResultCore'))$('gd3PlayResultCore').classList.toggle('penaltyOnly',dead);if(dead&&!p.dataset.seeded){presetNext();p.dataset.seeded='1';}if(!on&&p)p.dataset.seeded='';syncPenaltyLegacy();updateSpeedHealth();}
 function officialNextFor(p){if(!$('gd3PenaltyPanel')||$('gd3PenaltyPanel').classList.contains('hidden'))return null;var status=$('gd3PenStatus').value;if(status==='Declined'||status==='Offsetting')return status==='Offsetting'?{quarter:p.quarter,down:p.down,distance:p.distance,fieldSide:p.fieldSide,yardLine:p.yardLine,drive:p.drive,possessionEnded:false,reason:'Offsetting penalty'}:null;return buildOfficialNext(A.E,p,{quarter:p.quarter,down:$('gd3NextDown').value,distance:$('gd3NextDistance').value,fieldSide:$('gd3NextSide').value,yardLine:$('gd3NextYard').value});}
 function penaltyReady(){if(!$('gd3PenaltyPanel')||$('gd3PenaltyPanel').classList.contains('hidden'))return true;if($('gd3PenStatus').value!=='Accepted')return true;var p=A.buildPlay?A.buildPlay():null;return !!(p&&p.officialNext);}
 function updatePickSixVisibility(){var int=A.sel&&A.sel.playType==='Pass'&&$('passResult')&&$('passResult').value==='Interception';if($('gd3TurnoverExtra'))$('gd3TurnoverExtra').classList.toggle('hidden',!int);if(!int&&$('gd3PickSix'))$('gd3PickSix').classList.remove('on');}
 function syncQuickStates(){syncHashButtons();syncBlitzButtons();syncCoverageButtons();updatePickSixVisibility();}
 function updateSpeedHealth(){var h=$('gd3SpeedHealth');if(!h)return;var t=A.sel&&A.sel.playType;if(!t){h.textContent='Choose Run, Pass, or Penalty';h.className='gd3SpeedHealth';return;}if((t==='Penalty'||penaltyTagged())&&!penaltyReady()){h.textContent='Penalty: enter the official next snap';h.className='gd3SpeedHealth warn';return;}var bits=[];if($('hash')&&$('hash').value==='NA')bits.push('hash ?');if(A.sel.front==null||A.sel.front==='NA')bits.push('front ?');if($('pressure')&&$('pressure').value==='NA')bits.push('blitz ?');h.textContent='READY TO SAVE'+(bits.length?' • '+bits.join(' • '):'');h.className='gd3SpeedHealth ready';}
 function wireSpeed(){
  ['gd3EndSide','gd3EndYard'].forEach(function(id){var e=$(id);if(!e)return;e.addEventListener('change',function(){if(id==='gd3EndSide'){var fixed=e.value==='50'||e.value==='GOAL';$('gd3EndYard').disabled=fixed;$('gd3EndYard').value=e.value==='50'?'50':'';}syncYardsFromSpot();});if(id==='gd3EndYard')e.addEventListener('input',syncYardsFromSpot);});
  if($('gd3Goal'))$('gd3Goal').onclick=function(){$('gd3EndSide').value='GOAL';$('gd3EndYard').disabled=true;$('gd3EndYard').value='';syncYardsFromSpot();};
  if($('yards')){$('yards').addEventListener('input',function(){syncSpotFromYards();renderGain();});$('yards').addEventListener('change',syncSpotFromYards);}
  ['side','yard','down','distance'].forEach(function(id){if($(id))$(id).addEventListener('change',syncSpotFromYards);});
  if($('hash'))$('hash').addEventListener('change',function(){syncHashButtons();updateSpeedHealth();});if($('pressure'))$('pressure').addEventListener('change',function(){syncBlitzButtons();updateSpeedHealth();});if($('postCoverage'))$('postCoverage').addEventListener('change',syncCoverageButtons);
  d.querySelectorAll('[data-group="playType"] .choice').forEach(function(b){b.addEventListener('click',function(){setTimeout(function(){updatePenaltyVisibility();updatePickSixVisibility();updateSpeedHealth();},0);});});d.querySelectorAll('[data-pass]').forEach(function(b){b.addEventListener('click',function(){setTimeout(function(){updatePickSixVisibility();updateSpeedHealth();},0);});});if($('passResult'))$('passResult').addEventListener('change',updatePickSixVisibility);
  if($('gd3PickSix'))$('gd3PickSix').onclick=function(){this.classList.toggle('on');updateSpeedHealth();};
  if($('gd3PenaltyToggle'))$('gd3PenaltyToggle').onclick=function(){setPenaltyTagged(!penaltyTagged());if(penaltyTagged()){presetNext();$('gd3PenaltyPanel').dataset.seeded='1';}updatePenaltyVisibility();};
  ['gd3PenType','gd3PenTeam','gd3PenStatus','gd3PenTiming','gd3NextDown','gd3NextDistance','gd3NextSide','gd3NextYard'].forEach(function(id){if($(id)){$(id).addEventListener('change',function(){if(id==='gd3NextSide'){$('gd3NextYard').disabled=$(id).value==='50';if($(id).value==='50')$('gd3NextYard').value='50';}syncPenaltyLegacy();updateSpeedHealth();});$(id).addEventListener('input',function(){syncPenaltyLegacy();updateSpeedHealth();});}});
 }
 injectCss();ensureMarkup();
 var oldBuild=A.buildPlay;if(oldBuild)A.buildPlay=function(){var p=oldBuild.call(A);syncPenaltyLegacy();if($('gd3PickSix')&&$('gd3PickSix').classList.contains('on')&&p.passResult==='Interception'){p.opponentPoints=6;ensureTag(p,'Interception');ensureTag(p,'Turnover');ensureTag(p,'Pick Six');removeTag(p,'Touchdown');}var on=p.playType==='Penalty'||penaltyTagged();if(on){p.penalty=p.penalty||{};p.penalty.type=$('gd3PenType').value;p.penalty.team=$('gd3PenTeam').value;p.penalty.status=$('gd3PenStatus').value;p.penalty.timing=$('gd3PenTiming').value;var next=officialNextFor(p);if(next){p.officialNext=next;p.penalty.officialNext=next;p.penalty.yards=Math.round(A.E.fieldAbs(next.fieldSide,next.yardLine)-A.E.fieldAbs(p.fieldSide,p.yardLine));}if(p.playType==='Penalty')p.yards=0;}return p;};
 var oldApply=A.applyPlay;if(oldApply)A.applyPlay=function(p){var before=cloneScore(A.state.score),n=oldApply.call(A,p),pts=opponentPoints(p),saved=A.state.plays[A.state.plays.length-1];if(pts){A.state.score=A.state.score||cloneScore(before);A.state.score.them=before.them+pts;if(saved){saved.scoreOpponentAutoPoints=pts;saved.scoreAfter=cloneScore(A.state.score);}A.save('opponent-defensive-score');}return n;};
 var oldReplace=A.replaceLastPlay;if(oldReplace)A.replaceLastPlay=function(p){if(!A.state.plays.length)return oldReplace.call(A,p);var old=A.state.plays[A.state.plays.length-1],current=cloneScore(A.state.score),remove=Number(old.scoreOpponentAutoPoints)||0;A.state.score.them=Math.max(0,current.them-remove);var n=oldReplace.call(A,p);if(!n){A.state.score=current;return n;}var pts=opponentPoints(p),saved=A.state.plays[A.state.plays.length-1];A.state.score.them+=pts;if(saved){saved.scoreOpponentAutoPoints=pts;saved.scoreAfter=cloneScore(A.state.score);}A.save('edit-last-opponent-score');return n;};
 var oldUndo=A.undo;if(oldUndo)A.undo=function(){var p=oldUndo.call(A);if(p&&p.scoreOpponentAutoPoints){A.state.score.them=Math.max(0,(Number(A.state.score.them)||0)-Number(p.scoreOpponentAutoPoints));A.save('undo-opponent-score');}return p;};
 var oldReset=A.resetEntry;if(oldReset)A.resetEntry=function(){var r=oldReset.apply(A,arguments);setTimeout(function(){syncSpotFromYards();syncQuickStates();if($('gd3PickSix'))$('gd3PickSix').classList.remove('on');if($('gd3PenaltyPanel')){$('gd3PenaltyPanel').classList.add('hidden');$('gd3PenaltyPanel').dataset.seeded='';}if($('gd3PenaltyToggle'))$('gd3PenaltyToggle').classList.remove('on');updateSpeedHealth();},0);return r;};
 var oldAll=A.renderAll;if(oldAll)A.renderAll=function(){var r=oldAll.apply(A,arguments);syncSpotFromYards();syncQuickStates();updatePenaltyVisibility();updateSpeedHealth();return r;};
 var save=$('save');if(save&&!save.dataset.gd3SaveGuard){save.dataset.gd3SaveGuard='1';var oldSave=save.onclick;save.onclick=function(e){if((A.sel.playType==='Penalty'||penaltyTagged())&&!penaltyReady()){A.msg&&A.msg('Penalty: enter the official next down, distance and spot');var p=$('gd3PenaltyPanel');if(p&&p.scrollIntoView)p.scrollIntoView({block:'nearest'});return;}return oldSave&&oldSave.call(this,e);};}
 updateSpeedHealth();
 return A;
}
return{spotAbs:spotAbs,spotFromAbs:spotFromAbs,yardsBetween:yardsBetween,endFromYards:endFromYards,buildOfficialNext:buildOfficialNext,opponentPoints:opponentPoints,install:install};
});
