(function(root,factory){
'use strict';
var C=factory();if(typeof module==='object'&&module.exports){module.exports=C;return;}if(root.FNIQ)C.install(root.FNIQ,root);
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
var PIN_KEY='fniq_q27_pins_v1',SIZE_KEY='fniq_q27_control_size_v1';
var CFG={formation:{id:'formation',label:'Formation',max:5},motion:{id:'motion',label:'Motion',max:5},coverage:{id:'coverage',label:'Initial Coverage',max:5},runType:{id:'attackDetail',label:'Run Type',max:5}};
var RUN_TYPES=['Inside Zone','Outside Zone','Counter','Power','Draw'];
function safeParse(x,d){try{var v=JSON.parse(x);return v&&typeof v==='object'?v:d;}catch(e){return d;}}
function normalizeSize(v){return['standard','large','xl'].indexOf(v)>=0?v:'standard';}
function defaults(){return{formation:[],motion:[],coverage:['Cover 1','Cover 2','Cover 3'],runType:['Inside Zone','Outside Zone','Counter']};}
function install(A,root){
 if(!A||!root.document||A.__quality27Qol)return A;A.__quality27Qol=true;var d=root.document,fixIntent=false,lastShown=0;
 function $(id){return d.getElementById(id);}function fire(el,type){if(el)el.dispatchEvent(new Event(type||'change',{bubbles:true}));}
 function readPins(){var p;try{p=safeParse(root.localStorage.getItem(PIN_KEY),defaults());}catch(e){p=defaults();}var out=defaults();Object.keys(CFG).forEach(function(k){if(Array.isArray(p[k]))out[k]=p[k].map(String).filter(Boolean).slice(0,CFG[k].max);});return out;}
 function writePins(p){try{root.localStorage.setItem(PIN_KEY,JSON.stringify(p));}catch(e){}renderPins();renderSettings();}
 function readSize(){try{return normalizeSize(root.localStorage.getItem(SIZE_KEY));}catch(e){return'standard';}}
 function writeSize(v){v=normalizeSize(v);try{root.localStorage.setItem(SIZE_KEY,v);}catch(e){}applySize(v);renderSettings();}
 function injectCss(){if($('quality27Css'))return;var l=d.createElement('link');l.id='quality27Css';l.rel='stylesheet';l.href='quality27-qol.css?v=quality27';d.head.appendChild(l);}
 function applySize(v){v=normalizeSize(v);var h=d.documentElement;h.classList.remove('fniqQ27SizeStandard','fniqQ27SizeLarge','fniqQ27SizeXl');h.classList.add(v==='large'?'fniqQ27SizeLarge':v==='xl'?'fniqQ27SizeXl':'fniqQ27SizeStandard');h.dataset.q27ControlSize=v;}
 function available(k){var e=$(CFG[k].id),vals=[];if(k==='runType')return RUN_TYPES.slice();if(e&&e.tagName==='SELECT')[].forEach.call(e.options,function(o){var v=String(o.value||'').trim();if(v&&v!=='NA'&&v!=='Unknown'&&vals.indexOf(v)<0)vals.push(v);});if(k==='motion'&&vals.indexOf('No Motion')>=0)vals=vals.filter(function(v){return v!=='No Motion';});return vals;}
 function makePinButton(k,v,fixed){var b=d.createElement('button');b.type='button';b.className='q27PinnedBtn'+(fixed?' q27PinnedFixed':'');b.textContent=v==='No Motion'?'NO MOTION':v;b.dataset.value=v;b.onclick=function(){var e=$(CFG[k].id);if(!e)return;if(e.tagName==='SELECT'){if(![].some.call(e.options,function(o){return o.value===v;})){var o=d.createElement('option');o.value=v;o.textContent=v;e.appendChild(o);}e.value=v;}else e.value=v;if(k==='coverage'||k==='motion')e.dataset.q24Touched='1';fire(e,'input');fire(e,'change');syncPinState(k);updateMissing();};return b;}
 function pinHost(k){var e=$(CFG[k].id);if(!e)return null;var id='q27Pins-'+k,bar=$(id);if(!bar){bar=d.createElement('div');bar.id=id;bar.className='q27PinnedRow q27Pinned-'+k;e.parentElement.insertBefore(bar,e);}return bar;}
 function syncPinState(k){var e=$(CFG[k].id),bar=$('q27Pins-'+k);if(!e||!bar)return;bar.querySelectorAll('button').forEach(function(b){b.classList.toggle('on',String(e.value)===b.dataset.value);});}
 function renderPins(){var p=readPins();Object.keys(CFG).forEach(function(k){var bar=pinHost(k);if(!bar)return;bar.innerHTML='';if(k==='motion')bar.appendChild(makePinButton(k,'No Motion',true));p[k].forEach(function(v){if(k==='runType'||available(k).indexOf(v)>=0)bar.appendChild(makePinButton(k,v,false));});bar.classList.toggle('hidden',k==='runType'&&!(A.sel&&A.sel.playType==='Run'));syncPinState(k);});var oldCov=$('q24CoverageQuick'),oldMotion=$('q24MotionQuick'),oldAttack=$('q24AttackQuick');if(oldCov)oldCov.classList.add('q27LegacyQuick');if(oldMotion)oldMotion.classList.add('q27LegacyQuick');if(oldAttack)oldAttack.classList.toggle('q27LegacyRunQuick',!!(A.sel&&A.sel.playType==='Run'));}
 function settingsHost(){return $('settingsLeft')||$('settingsRight');}
 function ensureSettings(){var host=settingsHost();if(!host||$('q27Settings'))return;var c=d.createElement('div');c.id='q27Settings';c.className='card q27Settings';host.insertBefore(c,host.firstChild);renderSettings();}
 function renderSettings(){var c=$('q27Settings');if(!c)return;var p=readPins(),size=readSize();c.innerHTML='<div class="cardhead"><div><h2 class="section">Game-speed controls</h2><p class="muted">Pin the calls you use most. Every full dropdown stays available.</p></div><span class="tinybadge">THIS DEVICE</span></div><div class="q27SizeSetting"><label class="label">Control size</label><div class="q27SizeChoices"><button data-q27-size="standard">Standard</button><button data-q27-size="large">Large</button><button data-q27-size="xl">Extra Large</button></div><small>Reflows controls instead of zooming the page.</small></div><div id="q27PinSettings"></div>';
 c.querySelectorAll('[data-q27-size]').forEach(function(b){b.classList.toggle('on',b.dataset.q27Size===size);b.onclick=function(){writeSize(b.dataset.q27Size);};});var ph=$('q27PinSettings');Object.keys(CFG).forEach(function(k){var vals=available(k),wrap=d.createElement('div');wrap.className='q27PinGroup';wrap.innerHTML='<div class="q27PinHead"><strong>'+CFG[k].label+'</strong><span>'+p[k].length+'/'+CFG[k].max+' pinned</span></div><div class="q27PinOptions"></div>';var opts=wrap.querySelector('.q27PinOptions');if(!vals.length){opts.innerHTML='<small class="muted">Use the tracker dropdown once to load available options.</small>';}vals.forEach(function(v){var b=d.createElement('button');b.type='button';b.className='q27PinOption';b.textContent=v;b.setAttribute('aria-pressed',p[k].indexOf(v)>=0?'true':'false');b.classList.toggle('on',p[k].indexOf(v)>=0);b.onclick=function(){var now=readPins(),i=now[k].indexOf(v);if(i>=0)now[k].splice(i,1);else{if(now[k].length>=CFG[k].max){A.msg&&A.msg('Maximum '+CFG[k].max+' '+CFG[k].label+' pins');return;}now[k].push(v);}writePins(now);};opts.appendChild(b);});ph.appendChild(wrap);});}
 function missing(){var out=[],q=function(sel){return d.querySelector(sel);},v=function(id){var e=$(id);return e?String(e.value||''):'';};if(v('hash')==='NA'||!v('hash'))out.push(['Hash','hash']);if(v('formation')==='NA'||!v('formation'))out.push(['Formation','formation']);if(!v('personnel').trim())out.push(['Personnel','personnel']);if(!q('[data-group="front"] .choice.on'))out.push(['Front','front']);if(!q('[data-group="safeties"] .choice.on'))out.push(['Safeties','safeties']);var cov=$('coverage');if(!cov||(cov.value==='NA'&&cov.dataset.q24Touched!=='1'))out.push(['Coverage','coverage']);if(!q('[data-group="box"] .choice.on'))out.push(['Box','box']);var mot=$('motion');if(!mot||((mot.value==='NA'||!mot.value)&&mot.dataset.q24Touched!=='1'))out.push(['Motion','motion']);return out;}
 function target(key){if(['front','safeties','box'].indexOf(key)>=0)return d.querySelector('[data-group="'+key+'"]');return $(key);}
 function focusMissing(key){var e=target(key);if(!e)return;var wrap=e.closest('.speedField,.q24Field,.contextrow>div,.speedDefenseGrid>div')||e.parentElement||e,r=wrap.getBoundingClientRect();if(r.top<0||r.bottom>root.innerHeight)wrap.scrollIntoView({block:'nearest',behavior:'smooth'});wrap.classList.remove('q27FieldPulse');void wrap.offsetWidth;wrap.classList.add('q27FieldPulse');setTimeout(function(){wrap.classList.remove('q27FieldPulse');},1100);var f=e.matches&&e.matches('select,input,button')?e:e.querySelector('select,input,button');if(f)f.focus({preventScroll:true});}
 function updateMissing(){var count=$('q24CaptureCount'),host=$('q24CaptureMissing'),m=missing();if(!count||!host)return;if(!m.length){count.textContent='PRE-SNAP COMPLETE';host.innerHTML='<span class="q27CompleteText">All 8 key fields charted</span>';host.classList.add('q27Complete');return;}count.textContent=m.length+' field'+(m.length===1?'':'s')+' missing';host.classList.remove('q27Complete');host.innerHTML='';var intro=d.createElement('span');intro.className='q27MissingLead';intro.textContent='Tap to finish:';host.appendChild(intro);m.forEach(function(x){var b=d.createElement('button');b.type='button';b.className='q27MissingBtn';b.textContent=x[0].toUpperCase();b.onclick=function(){focusMissing(x[1]);};host.appendChild(b);});}
 function bindMissing(){['hash','formation','personnel','coverage','motion'].forEach(function(id){var e=$(id);if(e&&!e.dataset.q27MissingBound){e.dataset.q27MissingBound='1';e.addEventListener('change',function(){setTimeout(updateMissing,0);});e.addEventListener('input',function(){setTimeout(updateMissing,0);});}});['front','safeties','box'].forEach(function(g){d.querySelectorAll('[data-group="'+g+'"] .choice').forEach(function(b){if(b.dataset.q27MissingBound)return;b.dataset.q27MissingBound='1';b.addEventListener('click',function(){setTimeout(updateMissing,0);});});});}
 function fieldText(s){return !s?'':s.fieldSide==='50'?'50':(s.fieldSide==='OWN'?'Own ':'Opp ')+s.yardLine;}
 function ord(n){return Number(n)===1?'1st':Number(n)===2?'2nd':Number(n)===3?'3rd':'4th';}
 function resultText(p){var parts=[];if(p.playType)parts.push(p.playType);if(p.attackDetail&&p.attackDetail!=='NA')parts.push(p.attackDetail);if(p.passResult)parts.push(p.passResult);var y=Number(A.E&&A.E.officialNetYards?A.E.officialNetYards(p):p.yards)||0;parts.push((y>=0?'+':'')+y+' yd');return parts.join(' • ');}
 function ensureSavedBar(){var live=$('live'),snap=live&&live.querySelector('.snapbar');if(!live||!snap)return null;var b=$('q27SavedBar');if(!b){b=d.createElement('div');b.id='q27SavedBar';b.className='q27SavedBar hidden';b.innerHTML='<div class="q27SavedCopy"><strong id="q27SavedTitle">PLAY SAVED</strong><span id="q27SavedResult"></span><small id="q27SavedNext"></small></div><div class="q27SavedActions"><button id="q27FixLast" type="button" class="btn primary">Fix Last Play</button><button id="q27UndoLast" type="button" class="btn">Undo Last</button><button id="q27SavedDismiss" type="button" class="q27SavedDismiss" aria-label="Dismiss">×</button></div>';snap.insertAdjacentElement('afterend',b);$('q27FixLast').onclick=function(){fixIntent=true;var u=$('undo');if(u)u.click();};$('q27UndoLast').onclick=function(){fixIntent=false;var u=$('undo');if(u)u.click();};$('q27SavedDismiss').onclick=hideSaved;}return b;}
 function hideSaved(){var b=$('q27SavedBar');if(b)b.classList.add('hidden');d.documentElement.classList.remove('q27SavedVisible');}
 function showSaved(p,n){var b=ensureSavedBar();if(!b||!p)return;lastShown=p.number||0;$('q27SavedTitle').textContent='PLAY '+p.number+' SAVED';$('q27SavedResult').textContent=resultText(p);$('q27SavedNext').textContent=n&&n.possessionEnded?'Drive ended • '+(n.reason||'possession change'):(n?'Next: '+ord(n.down)+' & '+n.distance+' • '+fieldText(n):'Saved');b.classList.remove('hidden');d.documentElement.classList.add('q27SavedVisible');clearTimeout(showSaved.timer);showSaved.timer=setTimeout(hideSaved,7000);}
 function bindPlayType(){d.querySelectorAll('[data-group="playType"] .choice').forEach(function(b){if(b.dataset.q27Bound)return;b.dataset.q27Bound='1';b.addEventListener('click',function(){setTimeout(renderPins,30);});});var ad=$('attackDetail');if(ad&&!ad.dataset.q27Bound){ad.dataset.q27Bound='1';ad.addEventListener('change',function(){syncPinState('runType');});}}
 function prepare(){ensureSettings();applySize(readSize());renderPins();bindMissing();updateMissing();bindPlayType();ensureSavedBar();}
 injectCss();applySize(readSize());
 var oldApply=A.applyPlay;if(oldApply&&!A.__q27ApplyWrap){A.__q27ApplyWrap=true;A.applyPlay=function(p){var n=oldApply.apply(A,arguments);setTimeout(function(){showSaved(p,n);},0);return n;};}
 var oldUndo=A.undo;if(oldUndo&&!A.__q27UndoWrap){A.__q27UndoWrap=true;A.undo=function(){var p=oldUndo.apply(A,arguments);if(p){hideSaved();if(fixIntent)setTimeout(function(){A.msg&&A.msg('Play '+p.number+' removed — re-enter the corrected snap');fixIntent=false;},0);}return p;};}
 var oldRender=A.renderAll;if(oldRender&&!A.__q27RenderWrap){A.__q27RenderWrap=true;A.renderAll=function(){var r=oldRender.apply(A,arguments);prepare();return r;};}
 prepare();return A;
}
return{normalizeSize:normalizeSize,defaults:defaults,install:install,PIN_KEY:PIN_KEY,SIZE_KEY:SIZE_KEY};
});
