(function(root){
'use strict';
var A=root.FNIQ,E=A.E,modalFn=null;
function $(id){return document.getElementById(id)}A.$=$;
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}A.esc=esc;
function ord(n){return Number(n)===1?'1st':Number(n)===2?'2nd':Number(n)===3?'3rd':'4th'}A.ord=ord;
function fieldText(p){return p.fieldSide==='50'?'50':(p.fieldSide==='OWN'?'Own ':'Opp ')+p.yardLine}A.fieldText=fieldText;
function msg(t){var x=$('toast');x.textContent=t;x.classList.remove('hidden');clearTimeout(msg.timer);msg.timer=setTimeout(function(){x.classList.add('hidden')},1800)}A.msg=msg;
function confirmBox(t,x,fn){$('mTitle').textContent=t;$('mText').textContent=x;modalFn=fn;$('modal').classList.remove('hidden')}
$('mCancel').onclick=function(){$('modal').classList.add('hidden');modalFn=null};$('mYes').onclick=function(){var f=modalFn;$('modal').classList.add('hidden');modalFn=null;if(f)f()};
function intel(){if(A.renderLiveIntelligence)A.renderLiveIntelligence()}
A.screen=function(id){document.querySelectorAll('.screen').forEach(function(x){x.classList.toggle('on',x.id===id)});document.querySelectorAll('.nav button').forEach(function(x){x.classList.toggle('active',x.dataset.screen===id)});if(id==='iq'&&A.renderIQ)A.renderIQ();if(id==='live')intel()};document.querySelectorAll('.nav button').forEach(function(b){b.onclick=function(){A.screen(b.dataset.screen)}});
function contrast(hex){hex=String(hex||'').replace('#','');if(hex.length!==6)return'#06131a';var r=parseInt(hex.slice(0,2),16),g=parseInt(hex.slice(2,4),16),b=parseInt(hex.slice(4,6),16),y=(r*299+g*587+b*114)/1000;return y>145?'#06131a':'#ffffff'}
function applyBranding(){var b=A.state.branding||{},a=b.primary||'#62d6c8',s=b.secondary||'#829cff';document.documentElement.style.setProperty('--a',a);document.documentElement.style.setProperty('--b',s);document.documentElement.style.setProperty('--onA',contrast(a));document.documentElement.style.setProperty('--onB',contrast(s));$('brandPrimary').value=a;$('brandSecondary').value=s;var mark=$('brandMark');if(b.logo)mark.innerHTML='<img alt="Team logo" src="'+b.logo+'">';else{var name=(A.state.setup.team||'Friday Night').trim(),parts=name.split(/\s+/),initials=(parts[0]?parts[0][0]:'F')+(parts[1]?parts[1][0]:'N');mark.textContent=initials.toUpperCase()}}A.applyBranding=applyBranding;
['brandPrimary','brandSecondary'].forEach(function(id){$(id).addEventListener('input',function(){if(!A.state.branding)A.state.branding={};A.state.branding[id==='brandPrimary'?'primary':'secondary']=this.value;A.save();applyBranding()})});
$('brandLogo').addEventListener('change',function(){var file=this.files&&this.files[0];if(!file)return;if(file.size>4*1024*1024){msg('Logo file is too large');this.value='';return}var r=new FileReader();r.onload=function(){var img=new Image();img.onload=function(){var c=document.createElement('canvas'),max=160,scale=Math.min(1,max/Math.max(img.width,img.height));c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);A.state.branding.logo=c.toDataURL('image/png',.9);A.save();applyBranding();msg('Logo saved on this device')};img.src=r.result};r.readAsDataURL(file)});
$('removeLogo').onclick=function(){A.state.branding.logo='';A.save();$('brandLogo').value='';applyBranding();msg('Logo removed')};
function rosterRow(p){p=p||{};var d=document.createElement('div');d.className='roster';d.innerHTML='<input placeholder="#" value="'+esc(p.number)+'"><input placeholder="Player name" value="'+esc(p.name)+'"><input placeholder="Pos" value="'+esc(p.position)+'"><button class="btn">×</button>';d.querySelector('button').onclick=function(){d.remove();syncRoster()};d.querySelectorAll('input').forEach(function(i){i.oninput=syncRoster});$('roster').appendChild(d)}
function syncRoster(){A.state.roster=[];document.querySelectorAll('.roster').forEach(function(r){var x=r.querySelectorAll('input'),p={number:x[0].value.trim(),name:x[1].value.trim(),position:x[2].value.trim()};if(p.number||p.name||p.position)A.state.roster.push(p)});A.save();fillPlayers()}
function pval(p){return '#'+p.number+' '+p.name}function qbs(){return A.state.roster.filter(function(p){return String(p.position||'').trim().toUpperCase()==='QB'}).map(pval)}
function ensureQB(){var q=qbs();if(!A.state.activeQB||q.indexOf(A.state.activeQB)<0)A.state.activeQB=q[0]||null;$('qbButton').textContent='QB: '+(A.state.activeQB?A.state.activeQB.split(' ')[0]:'N/A')}
function fillPlayers(){['player','penPlayer'].forEach(function(id){var s=$(id),v=s.value;s.innerHTML='<option value="">Select</option><option>Unknown / N/A</option>';A.state.roster.forEach(function(p){var o=document.createElement('option');o.value=pval(p);o.textContent=o.value+(p.position?' ('+p.position+')':'');s.appendChild(o)});if([].some.call(s.options,function(o){return o.value===v}))s.value=v});ensureQB()}
$('qbButton').onclick=function(){var q=qbs();if(!q.length)return msg('Add a QB to roster');var i=q.indexOf(A.state.activeQB);A.state.activeQB=q[(i+1+q.length)%q.length];A.save();ensureQB();msg('Active QB '+A.state.activeQB)};
function subtitle(){$('subtitle').textContent=A.state.setup.opp?(A.state.setup.team||'Our Team')+' vs '+A.state.setup.opp+' • '+A.state.setup.date:'Live offensive charting + Game IQ';applyBranding()}
A.renderSetup=function(){$('team').value=A.state.setup.team||'';$('opp').value=A.state.setup.opp||'';$('date').value=A.state.setup.date||'';$('season').value=A.state.setup.season||'';$('roster').innerHTML='';if(A.state.roster.length)A.state.roster.forEach(rosterRow);else for(var i=0;i<6;i++)rosterRow();fillPlayers();subtitle()};
$('addPlayer').onclick=function(){rosterRow()};$('start').onclick=function(){syncRoster();A.state.setup={team:$('team').value.trim(),opp:$('opp').value.trim(),date:$('date').value,season:$('season').value.trim()};A.save();subtitle();hydrateSituation();A.screen('live');msg('Setup saved')};$('reset').onclick=function(){confirmBox('Reset game?','Clear all plays and reset to 1st & 10 at Own 25? Your roster and branding stay.',function(){A.resetGame();hydrateSituation();resetEntry();A.renderAll();msg('Game reset')})};
function choose(g,v){A.sel[g]=v;var w=document.querySelector('[data-group="'+g+'"]');if(w)w.querySelectorAll('.choice').forEach(function(b){b.classList.toggle('on',v!==null&&b.dataset.v===String(v))});if(g==='playType')playUI();updateEntrySummary();intel()}A.choose=choose;
document.querySelectorAll('[data-group]').forEach(function(w){w.querySelectorAll('.choice').forEach(function(b){b.onclick=function(){choose(w.dataset.group,b.dataset.v);renderMeta();preview()}})});
document.querySelectorAll('[data-y]').forEach(function(b){b.onclick=function(){$('yards').value=b.dataset.y;preview();updateEntrySummary()}});document.querySelectorAll('[data-step-y]').forEach(function(b){b.onclick=function(){$('yards').value=String((+$('yards').value||0)+(+b.dataset.stepY||0));preview();updateEntrySummary()}});document.querySelectorAll('.tag').forEach(function(b){b.onclick=function(){b.classList.toggle('on');penaltyUI();preview();updateEntrySummary()}});
function tags(){return [].map.call(document.querySelectorAll('.tag.on'),function(b){return b.dataset.tag})}A.tags=tags;
function penaltyUI(){$('penaltyPanel').classList.toggle('hidden',A.sel.playType!=='Penalty'&&tags().indexOf('Penalty')<0)}
function setPassResult(v){$('passResult').value=v;document.querySelectorAll('[data-pass]').forEach(function(b){b.classList.toggle('on',b.dataset.pass===v)});var qb=v==='Sack'||v==='Scramble';if(qb&&A.state.activeQB&&!$('player').value)$('player').value=A.state.activeQB;$('playerLabel').textContent=qb?'Quarterback':'Targeted receiver';preview();updateEntrySummary()}
document.querySelectorAll('[data-pass]').forEach(function(b){b.onclick=function(){setPassResult(b.dataset.pass)}});
function playUI(){var t=A.sel.playType,show=t==='Run'||t==='Pass';$('detail').classList.toggle('hidden',!show);$('passArea').classList.toggle('hidden',t!=='Pass');penaltyUI();if(show){var a=$('attackDetail');a.innerHTML='';(t==='Run'?['N/A','Inside','Off Tackle','Outside']:['N/A','Screen','Short','Intermediate','Deep']).forEach(function(x){var o=document.createElement('option');o.textContent=x;o.value=x==='N/A'?'NA':x;a.appendChild(o)});a.value='NA';$('detailLabel').textContent=t==='Run'?'Run lane':'Pass depth';$('playerLabel').textContent=t==='Run'?'Ball carrier':'Target / QB';if(t==='Pass')setPassResult('Complete')}preview();updateEntrySummary()}
$('passResult').onchange=function(){setPassResult(this.value)};
function saveContext(){A.setContext({formation:$('formation').value||'NA',personnel:$('personnel').value.trim()})}
$('formation').addEventListener('change',function(){saveContext();intel()});$('personnel').addEventListener('input',saveContext);$('personnel').addEventListener('change',saveContext);
function readSituation(){return E.normalizeSituation({quarter:$('quarter').value,down:+$('down').value,distance:+$('distance').value,fieldSide:$('side').value,yardLine:$('side').value==='50'?50:+$('yard').value})}A.readSituation=readSituation;
function syncSituation(){A.setCurrent(readSituation());renderMeta();preview();intel()}
function hydrateSituation(){var s=E.normalizeSituation(A.state.current);$('quarter').value=s.quarter;$('down').value=s.down;$('distance').value=s.distance;$('side').value=s.fieldSide;$('yard').value=s.yardLine;renderMeta()}A.hydrateSituation=hydrateSituation;
['quarter','down','distance','side','yard'].forEach(function(id){$(id).addEventListener('change',syncSituation);if(id==='distance'||id==='yard')$(id).addEventListener('input',syncSituation)});
function buildPlay(){var s=readSituation(),hasPen=A.sel.playType==='Penalty'||tags().indexOf('Penalty')>=0;return{number:A.state.plays.length+1,drive:A.state.drive,quarter:s.quarter,down:s.down,distance:s.distance,fieldSide:s.fieldSide,yardLine:s.yardLine,front:A.sel.front||'NA',safeties:A.sel.safeties===null?'NA':A.sel.safeties,box:A.sel.box||'NA',formation:$('formation').value||'NA',coverage:$('coverage').value||'NA',postCoverage:$('postCoverage').value||'NA',playType:A.sel.playType,player:$('player').value||'Unknown / N/A',passResult:A.sel.playType==='Pass'?$('passResult').value:'',attackDetail:['Run','Pass'].indexOf(A.sel.playType)>=0?($('attackDetail').value||'NA'):'NA',yards:+$('yards').value||0,tags:tags(),personnel:$('personnel').value.trim()||'NA',motion:$('motion').value.trim()||'NA',pressure:$('pressure').value||'NA',direction:$('direction').value,hash:$('hash').value,concept:$('concept').value.trim(),notes:$('notes').value.trim(),penalty:hasPen?{type:$('penType').value,timing:$('penTiming').value,team:$('penTeam').value,player:$('penPlayer').value,status:$('penStatus').value,distance:+$('penDistance').value||0,netOverride:$('penNetOverride').value===''?null:+$('penNetOverride').value,yards:+$('penYards').value||0,effect:$('penEffect').value}:null}}A.buildPlay=buildPlay;
function preview(){var x=$('penaltyPreview');if(!x)return;var p=buildPlay();if(!p.playType){x.textContent='';return}var n=E.nextSituation(p);x.textContent='Next snap: '+ord(n.down)+' & '+n.distance+' • '+fieldText(n)+(n.possessionEnded?' • Drive ended':'')}
['penType','penTiming','penTeam','penStatus','penDistance','penNetOverride','penYards','penEffect','yards','attackDetail','player','coverage','postCoverage','motion','pressure','direction','hash','concept'].forEach(function(id){$(id).addEventListener('change',function(){preview();updateEntrySummary();intel()});if(['penDistance','penNetOverride','penYards','yards','concept'].indexOf(id)>=0)$(id).addEventListener('input',function(){preview();updateEntrySummary();intel()})});
function updateEntrySummary(){var p=buildPlay(),bits=[];if(p.front!=='NA'||p.safeties!=='NA'||p.box!=='NA')bits.push((p.front||'NA')+'D • '+(p.safeties||'NA')+'H • '+(p.box||'NA')+' box');if(p.formation&&p.formation!=='NA')bits.push(p.formation);if(p.playType)bits.push(p.playType+(p.attackDetail&&p.attackDetail!=='NA'?' / '+p.attackDetail:''));if(p.player&&p.player!=='Unknown / N/A'&&p.playType!=='Penalty'&&p.playType!=='No Play')bits.push(p.player);if(p.postCoverage&&p.postCoverage!=='NA')bits.push('Post: '+p.postCoverage);if(p.playType)bits.push((p.yards>=0?'+':'')+p.yards+' yds');$('entrySummary').textContent=p.playType?bits.join('  |  '):'Choose Run, Pass, Penalty, or No Play';var missing=[];if(A.sel.front===null||A.sel.safeties===null||A.sel.box===null)missing.push('defense');if((p.playType==='Run'||p.playType==='Pass')&&p.player==='Unknown / N/A')missing.push('player');$('entrySub').textContent=missing.length?'Missing '+missing.join(' + ')+' will save as N/A.':'';var h=$('entryHealth');if(!p.playType){h.textContent='Choose play type';h.className='health partial'}else if(missing.length){h.textContent='Ready • '+missing.length+' unknown';h.className='health partial'}else{h.textContent='Ready to save';h.className='health ready'}}
$('save').onclick=function(){var p=buildPlay();if(!p.playType)return msg('Choose a play type');if(p.playType==='Pass'&&['Sack','Scramble'].indexOf(p.passResult)>=0&&p.player!=='Unknown / N/A')A.state.activeQB=p.player;var n=A.applyPlay(p);hydrateSituation();resetEntry();A.renderAll();msg(n.possessionEnded?'Play '+p.number+' saved — '+n.reason+'. Set next drive start spot.':'Play '+p.number+' saved')};
$('undo').onclick=function(){if(!A.state.plays.length)return msg('No play to undo');var p=A.state.plays[A.state.plays.length-1];confirmBox('Undo Play '+p.number+'?','Restore the exact pre-snap situation and remove this play.',function(){A.undo();hydrateSituation();resetEntry();A.renderAll();msg('Play removed — situation restored')})};
$('newDrive').onclick=function(){var has=A.state.plays.some(function(p){return p.drive===A.state.drive});if(has&&!A.state.awaitingPossessionStart)A.state.drive++;A.state.awaitingPossessionStart=false;A.state.current.down=1;A.state.current.distance=10;A.save();hydrateSituation();A.renderAll();msg('Drive '+A.state.drive+' ready — set start spot')};
function copyLook(p){choose('front',p.front);choose('safeties',p.safeties);choose('box',p.box)}
$('lastLook').onclick=function(){if(!A.state.plays.length)return msg('No previous look');copyLook(A.state.plays[A.state.plays.length-1]);msg('Last defensive look copied')};
$('lastContext').onclick=function(){if(!A.state.plays.length)return msg('No previous context');var p=A.state.plays[A.state.plays.length-1];copyLook(p);$('formation').value=p.formation||'NA';$('personnel').value=p.personnel&&p.personnel!=='NA'?p.personnel:'';saveContext();updateEntrySummary();intel();msg('Last look + offensive context copied')};
$('unknownLook').onclick=function(){choose('front','NA');choose('safeties','NA');choose('box','NA');$('coverage').value='NA';$('pressure').value='NA';$('postCoverage').value='NA';updateEntrySummary();intel();msg('Defense marked unknown')};$('clearEntry').onclick=function(){resetEntry();msg('Entry cleared — formation/personnel kept')};
function resetEntry(){['front','safeties','box','playType'].forEach(function(g){choose(g,null)});$('formation').value=A.state.context&&A.state.context.formation||'NA';$('personnel').value=A.state.context&&A.state.context.personnel||'';$('coverage').value='NA';$('postCoverage').value='NA';$('player').value='';$('passResult').value='Complete';$('attackDetail').innerHTML='<option value="NA">N/A</option>';$('attackDetail').value='NA';$('yards').value=0;$('motion').value='';$('pressure').value='NA';$('direction').value='NA';$('hash').value='NA';$('concept').value='';$('notes').value='';$('penType').value='';$('penTiming').value='NA';$('penTeam').value='';$('penPlayer').value='';$('penStatus').value='';$('penDistance').value=0;$('penNetOverride').value='';$('penYards').value=0;$('penEffect').value='REPEAT';document.querySelectorAll('.tag').forEach(function(b){b.classList.remove('on')});document.querySelectorAll('[data-pass]').forEach(function(b){b.classList.toggle('on',b.dataset.pass==='Complete')});playUI();if(A.syncPenaltyNet)A.syncPenaltyNet();updateEntrySummary();intel()}A.resetEntry=resetEntry;
function renderMeta(){var s=E.normalizeSituation(A.state.current);$('headline').textContent=ord(s.down)+' & '+s.distance;$('fieldline').textContent=fieldText(s)+' • '+s.quarter+(A.state.awaitingPossessionStart?' • NEW DRIVE START':'');$('playNum').textContent='Play '+(A.state.plays.length+1);$('driveNum').textContent='Drive '+A.state.drive;ensureQB();updateEntrySummary()}
function resolvedCoverage(p){return p.postCoverage&&p.postCoverage!=='NA'?(p.postCoverage==='Same as pre-snap'?(p.coverage||'NA'):p.postCoverage):(p.coverage||'NA')}
function sumPlay(p){var d=p.attackDetail&&p.attackDetail!=='NA'?p.attackDetail+' ':'';var y=E.officialNetYards(p),cov=resolvedCoverage(p);return d+p.playType+(p.passResult?' '+p.passResult:'')+' • '+p.player+' • '+(y>=0?'+':'')+y+(cov!=='NA'?' • '+cov:'')}
function recent(){var e=$('recent');if(!A.state.plays.length){e.innerHTML='<div class="muted">No plays logged.</div>';return}e.innerHTML=A.state.plays.slice(-6).reverse().map(function(p){var n=p.next?(' → '+ord(p.next.down)+' & '+p.next.distance+' '+fieldText(p.next)):'';return'<div class="play"><b>Play '+p.number+'</b> <span class="muted">'+p.quarter+' • '+ord(p.down)+' & '+p.distance+' • '+fieldText(p)+'</span><div>'+esc(sumPlay(p))+'</div><div class="muted">'+p.front+'D / '+p.safeties+'H / '+p.box+' box'+(p.pressure&&p.pressure!=='NA'?' • '+esc(p.pressure):'')+(p.penalty&&p.penalty.type?' • '+esc(p.penalty.type):'')+n+'</div></div>'}).join('')}
function drive(){var x=A.state.plays.filter(function(p){return p.drive===A.state.drive}),y=x.reduce(function(s,p){return s+E.officialNetYards(p)},0);$('driveSummary').textContent=x.length?x.length+' plays • '+y+' net yards • '+x.filter(E.isFirstDownResult).length+' first downs':(A.state.awaitingPossessionStart?'New drive — set starting yard line.':'No plays this drive.')}
function typingTarget(){var e=document.activeElement;return e&&['INPUT','TEXTAREA','SELECT'].indexOf(e.tagName)>=0}
document.addEventListener('keydown',function(e){if(!e.altKey||typingTarget())return;if(e.key==='Enter'){$('save').click();e.preventDefault()}else if(e.key.toLowerCase()==='l'){$('lastLook').click();e.preventDefault()}else if(e.key.toLowerCase()==='u'){$('unknownLook').click();e.preventDefault()}});
A.renderAll=function(){renderMeta();recent();drive();if(A.renderIQ)A.renderIQ();intel();subtitle()};
A.initUI=function(){A.renderSetup();hydrateSituation();resetEntry();A.renderAll()};
})(window);
