#!/usr/bin/env bash
set -euo pipefail
REPORT=qa-quality26-proof.txt
: > "$REPORT"
run(){ label="$1"; shift; echo "=== $label ===" | tee -a "$REPORT"; "$@" 2>&1 | tee -a "$REPORT"; echo "PASS: $label" | tee -a "$REPORT"; echo | tee -a "$REPORT"; }
run_shell(){ label="$1"; shift; echo "=== $label ===" | tee -a "$REPORT"; bash -lc "$*" 2>&1 | tee -a "$REPORT"; echo "PASS: $label" | tee -a "$REPORT"; echo | tee -a "$REPORT"; }
run_shell "JavaScript syntax sweep" 'for f in *.js; do node --check "$f"; done'
run "Game-state smoke" node qa-smoke.js
run "Durability" node qa-durability.js
run "Settings" node qa-settings.js
run "Relational analytics" node qa-analytics-relations.js
run "Booth workflow" node qa-booth-workflow.js
run "Penalty hardening" node qa-penalty-hardening.js
run "Quality26 football flow" node qa-football-flow26.js
run "Prior-request regression contract" node qa-history-regression.js
run "Game IQ search" node qa-game-iq-search.js
run "QB facets" node qa-qb-facets.js
run "Coach language" node qa-coach-language.js
run "Game-day regression" node qa-game-day-fixes.js
run "Game IQ 2" node qa-game-iq-pro.js
run "Game IQ destructive" node qa-game-iq-pro-destructive.js
run "First-down and Saved Views" node qa-game-iq-polish.js
run "Game IQ 1000-cycle stability" node qa-game-iq-stability.js
run "Destructive beta" node qa-destructive-beta.js
run "Live correction" node qa-live-correction.js
run "Quick stats drilldowns" node qa-game-iq-summary.js
run "Quality24 speed and confidence" node qa-quality24.js
run_shell "Quality26 release architecture" 'grep -q "tooltip-polish.js" app.js && grep -q "penalty-hardening.js" app.js && grep -q "run-type-stability.js" app.js && grep -q "pick-six.js" app.js && grep -q "live-correction.js" app.js && grep -q "box-ui-v19.js" app.js && grep -q "game-iq-summary.js" app.js && grep -q "quality24.js" app.js && grep -q "tracker-layout-polish.js" app.js && grep -q "box-ux25.js" app.js && grep -q "football-flow26.js" app.js && grep -q "quality26-context-results.js" app.js && ! grep -q "game-day-3.js" app.js && ! grep -q "speed-guard.js" app.js && ! grep -q "game-iq-v3.js" app.js && grep -q "v=quality26" app.js && grep -Eq "app.js\?v=(safety23-final|quality24|quality24-final|quality25|quality25-final|quality26|quality26-final)" index.html && grep -q "football-flow26.css?v=flow26" football-flow26.js && grep -q "quality24.css?v=quality24" quality24.js && grep -q "tracker-layout-polish.css?v=tracker25" tracker-layout-polish.js && grep -q "box-ux25.css?v=boxux25" box-ux25.js && grep -q "box-ui-v19.css?v=box23" box-ui-v19.js && grep -q "visual-polish.css?v=visual23" box-ui-v19.js && grep -q "adaptive-layout.css?v=adaptive23c" box-ui-v19.js && grep -q "pick-six.css?v=pick22" pick-six.js && grep -q "fniq_prod_v1" state.js && grep -q "fniq_recovery_v1" durability.js'
run_shell "Football preset contract" 'grep -q "False Start.*Offense.*Accepted.*5.*REPEAT.*DEAD" penalty-hardening.js && grep -q "Offside.*Defense.*Accepted.*5.*REPEAT.*DEAD" penalty-hardening.js && grep -q "Encroachment.*Defense.*Accepted.*5.*REPEAT.*DEAD" penalty-hardening.js && grep -q "Delay of Game.*Offense.*Accepted.*5.*REPEAT.*DEAD" penalty-hardening.js && grep -q "Holding.*Offense.*Accepted.*10.*COUNT.*LIVE" football-flow26.js'
run_shell "Quality26 booth-football contract" 'grep -q "half the distance" football-flow26.js && grep -q "Official net change" football-flow26.js && grep -q "Cancel Penalty" football-flow26.js && grep -q "Correct situation" football-flow26.js && grep -q "Pre-snap complete" football-flow26.js && grep -q "Fumble Lost" football-flow26.js && grep -q "Inside Zone.*Inside Zone" football-flow26.js && grep -q "Play results" quality26-context-results.js && grep -q "data-q26-tag=\"Penalty\"" qa-browser-football-flow26-release.js && grep -q "live-ball Penalty changed the underlying play type" qa-browser-football-flow26-release.js && grep -q "Permanent dead-ball regression" qa-browser-football-flow26-release.js && grep -q "Half-distance is automatic" qa-browser-football-flow26-release.js && grep -q "Situation correction must update the upcoming snap" qa-browser-football-flow26-release.js && grep -q "critical text too small" qa-browser-football-flow26-release.js'
run_shell "Run Type stability contract" 'grep -q "Inside Zone" run-type-stability.js && grep -q "Outside Zone" run-type-stability.js && grep -q "Counter" run-type-stability.js && grep -q "Power" run-type-stability.js && grep -q "Draw" run-type-stability.js && grep -q "Run Type" run-type-stability.js'
run_shell "Compact important-field contract" 'grep -q "boxSecondaryLookRow" box-ui-v19.js && grep -q "motion" box-ui-v19.js && grep -q "resets each play" box-ui-v19.js && grep -q "boxMainGrid" box-ui-v19.js && grep -q "primary tracker control off-screen" qa-browser-e2e.js && grep -q "position:fixed" box-ui-v19.css && grep -q "q24CoverageQuick" quality24.js && grep -q "q24MotionQuick" quality24.js && grep -q "No Motion" quality24.js && grep -q "q24AttackQuick" quality24.js && grep -q "q24ConceptQuick" quality24.js && grep -q "q24Capture" quality24.js && grep -q "fniqHurryUp" quality24.js && grep -q "trackerFinishCard" tracker-layout-polish.js && grep -q "trackerPenaltySaveDock" tracker-layout-polish.js && grep -q "q26RedundantConcept" football-flow26.js && grep -q "q26RedundantTags" football-flow26.js'
run_shell "Adaptive viewport and dead-space contract" 'grep -q "width:1475,height:668" qa-browser-responsive.js && grep -q "width:1366,height:768" qa-browser-responsive.js && grep -q "width:1920,height:1080" qa-browser-responsive.js && grep -q "width:2560,height:1440" qa-browser-responsive.js && grep -q "width:390,height:844" qa-browser-responsive.js && grep -q "width:844,height:390" qa-browser-responsive.js && grep -q "width:1366,height:768" qa-browser-tracker-workflow.js && grep -q "width:1660,height:900" qa-browser-tracker-workflow.js && grep -q "DEAD LOWER-RIGHT FAIL" qa-browser-tracker-workflow.js && grep -q "SCROLL FAIL" qa-browser-tracker-workflow.js && grep -q "penalty Save stays reachable" qa-browser-tracker-workflow.js && grep -q "normal run path stays in one viewport" qa-browser-tracker-workflow.js && grep -q "grid-column:1/-1" box-ux25.css && grep -q "grid-auto-rows:max-content" adaptive-layout.css && grep -q "max-height:700px" adaptive-layout.css && grep -q "min-width:1600px" adaptive-layout.css && grep -q "overflow-y:auto" adaptive-layout.css && grep -q "position:static!important" adaptive-layout.css && grep -q "shortSituationEdit" box-ui-v19.js && grep -q "boxHeaderSave" box-ui-v19.js && grep -q "align-items:start" football-flow26.css'
run_shell "Box ergonomics contract" 'grep -q "workstation-1660.*1660.*900" qa-browser-box-ergonomics.js && grep -q "text too small" qa-browser-box-ergonomics.js && grep -q "target too short" qa-browser-box-ergonomics.js && grep -q "dead lower-right area" qa-browser-box-ergonomics.js && grep -q "pre-snap dead internal space" qa-browser-box-ergonomics.js && grep -q "contrast too low" qa-browser-box-ergonomics.js && grep -q "unselected Blitz is visually over-colored" qa-browser-box-ergonomics.js && grep -q "min-height:36px" football-flow26.css && grep -q "font-size:12px" football-flow26.css'
run_shell "Game IQ confidence and data-quality contract" 'grep -q "repeated call with at least 50% success" quality24.js && grep -q "dead-ball looks still count as defensive evidence" quality24.js && grep -q "Charting health" quality24.js && grep -q "Low coverage means lower-confidence Game IQ" quality24.js && grep -q "two-play sample must never become a recommendation" qa-quality24.js && grep -q "repeated unsuccessful call must not become a positive recommendation" qa-quality24.js && grep -q "accepted dead-ball penalty must not enter offensive efficiency" qa-quality24.js && grep -q "charted dead-ball defensive look must remain usable evidence" qa-quality24.js && grep -q "legacy N/A must remain unknown" qa-quality24.js && grep -q "explicit No Motion must count as charted data" qa-quality24.js'
run_shell "Light-mode contract" 'grep -Fq "html[data-theme=\"light\"] #penaltyPanel.boxPenaltyInline" box-ui-v19.css && grep -q "Quick Game Stats values must remain readable in light mode" qa-browser-e2e.js && grep -Fq "html[data-theme=\"light\"] .q24Capture" quality24.css && grep -Fq "html[data-theme=\"light\"].fniqBoxUx25" box-ux25.css && grep -Fq "html[data-theme=\"light\"].fniqFootballFlow26" football-flow26.css'
run_shell "Historical UX contract" 'grep -q "DELAY=3200" tooltip-polish.js && grep -q "Save for quick access" game-iq-polish.js && grep -q "Returned for TD" pick-six.js && grep -q "explosiveRun" analytics.js && grep -q "explosivePass" analytics.js && grep -q "#iq .action.good" visual-polish.css && grep -q "#iq .action.bad" visual-polish.css'
run_shell "No broad observer regression in new layers" '! grep -q "MutationObserver" live-correction.js && ! grep -q "MutationObserver" live-runtime-stability.js && ! grep -q "MutationObserver" box-ui-v19.js && ! grep -q "MutationObserver" penalty-hardening.js && ! grep -q "MutationObserver" run-type-stability.js && ! grep -q "MutationObserver" game-iq-summary.js && ! grep -q "MutationObserver" quality24.js && ! grep -q "MutationObserver" tracker-layout-polish.js && ! grep -q "MutationObserver" box-ux25.js && ! grep -q "MutationObserver" football-flow26.js && ! grep -q "MutationObserver" quality26-context-results.js'
run "Static DOM references" node qa-static-dom.js
run_shell "Code size" 'wc -l *.js *.css index.html | tail -1'
echo "FINAL: PASS" | tee -a "$REPORT"
